from pathlib import Path
p=Path('docs/ui/desktop-production-workbench.js')
s=p.read_text()
s=s.replace("schema:4,fixture:","schema:5,productionView:null,mediaOpen:false,mediaFilter:'all',mediaSelection:null,mediaPreview:false,mediaImports:[],finishSection:'review',moment:0,fixture:")
s=s.replace("const at=()=>", "const workspace=()=>['edit','finish'].includes(S.view)?S.view:'production';\nconst moments=(i=at())=>S.shots[i]?.moments||[{time:0,label:'Einstellung',asset:'base'}];\nconst sketchCount=()=>S.have.board?S.shots.reduce((n,s,i)=>n+moments(i).filter(m=>m.asset).length,0):0;\nconst shotStart=(i=at())=>S.shots.slice(0,i).reduce((n,s)=>n+s.duration,0);\nconst at=()=>")
s=s.replace("trim:0}));S.editOrder", "trim:0,moments:i===4?momentExample():[{time:0,label:'Einstellung',asset:'base'}]}));S.editOrder")
s=s.replace("function makeShots()", "function momentExample(){return [{time:0,label:'Hebel greifen',asset:'1e',frame:0},{time:1.8,label:'Hebel herunterziehen',asset:'1e',frame:1},{time:3.6,label:'Maschine läuft an',asset:'1e',frame:2}];}\nfunction sketchPic(i,j=0){const m=moments(i)[j]||moments(i)[0];return !m.asset?'<div class=\"take-placeholder\">Sketch fehlt</div>':m.asset==='1e'?`<div class=\"thumb-image sketch moment-image\" role=\"img\" aria-label=\"${E(m.label)} · Shot ${E(S.shots[i].id)}\" style=\"--moment-y:${m.frame*50}%\"></div>`:pic(i);}\nfunction makeShots()")
s=s.replace("version:4,project:","version:5,workspace:workspace(),mediaPool:S.mediaOpen,sketchesPerShot:shot()?moments().length:0,project:")
s=s.replace("S.view=p;S.mode=", "if(workspace()==='production')S.productionView=S.view;S.view=p;if(workspace()==='production')S.productionView=p;S.mediaPreview=false;S.moment=0;S.mode=")
s=s.replace("<span class=\"grow\"></span>`+B('undo'", "<span class=\"grow\"></span>`+B('media','Medien',{attrs:`aria-pressed=\"${S.mediaOpen||workspace()==='edit'}\"`})+B('undo'")
start=s.index('function browser(){')
end=s.index('function surfaceTools()',start)
s=s[:start]+'''const mediaTypes={all:'Alle Medien',video:'Videos',audio:'Audio',sketch:'Sketches',reference:'References'};
function assets(){const list=[...S.mediaImports];if(S.track)list.push({id:'track',name:'Claude-mouse.wav',type:'audio',origin:'Zugewiesener Projekttrack'});
 if(S.have.board)S.shots.forEach((s,i)=>moments(i).forEach((m,j)=>{if(m.asset)list.push({id:`sketch-${i}-${j}`,name:`${s.id} · ${m.label}`,type:'sketch',shot:i,moment:j,origin:S.imported.board?'FilmFlow-Snapshot':'Storyboard · Demo-Sketch'});}));
 if(S.identities)[1,2,0,4].forEach((i,j)=>list.push({id:'identity-'+j,name:['Claude Mouse','AI Cat','Straße','Comfort Engine'][j],type:'reference',shot:i,origin:'Gerenderte Identitätsstudie · Beispiel'}));
 if(S.anchors)S.shots.forEach((s,i)=>{if(s.source==='KI-Video')list.push({id:'anchor-'+i,name:s.id+' · Shot-Anker',type:'reference',shot:i,origin:'Gerenderter Shot-Anker · Beispiel'});});
 Object.entries(S.takes).forEach(([i,takes])=>takes.forEach(t=>list.push({id:`take-${i}-${t}`,name:`${S.shots[i].id} · Take ${t}`,type:'video',shot:+i,take:t,origin:S.chosen[i]===t?'Ausgewählter Take · Standbild-Demo':'Weiterer Take · Standbild-Demo'})));
 return list;
}
const selectedAsset=()=>assets().find(a=>a.id===S.mediaSelection);
function assetImage(a){return a.type==='sketch'&&a.shot!==undefined?sketchPic(a.shot,a.moment):['reference','video'].includes(a.type)&&a.shot!==undefined?pic(a.shot,'reference'):a.type==='audio'?'<div class="media-audio" aria-label="Audiodatei">▂▅▃▇▅▂▆▃▅▂</div>':'<div class="take-placeholder">'+(a.type==='video'?'MOV · Beispielclip':'Bilddatei · Demo')+'</div>';}
function pool(){const all=assets(),items=all.filter(a=>S.mediaFilter==='all'||a.type===S.mediaFilter);return `<div class="pool-head"><b>Medienpool</b>${B('media-import','Importieren',{disabled:S.running})}</div><label class="pool-filter"><span class="sr-only">Medientyp</span><select data-media-filter>${Object.entries(mediaTypes).map(([v,t])=>`<option value="${v}" ${S.mediaFilter===v?'selected':''}>${t}${v==='all'?' · '+all.length:''}</option>`).join('')}</select></label><div class="media-grid">${items.map(a=>`<button data-do="asset:${a.id}" class="media-tile" aria-pressed="${a.id===S.mediaSelection}">${assetImage(a)}<span>${E(a.name)}</span><small>${a.type==='video'?'Video · Demo':mediaTypes[a.type]}</small></button>`).join('')||'<p class="meta">Keine Medien in dieser Auswahl.</p>'}</div><small class="pool-foot">Projektbestand · Zuweisung erfolgt ausdrücklich.</small>`;}
function browser(){
 const navrow=p=>`<button class="tree-row" data-open="${p}" aria-pressed="${S.view===p||(p==='brief'&&S.view==='design')}" aria-label="${labels[p]} · ${S.covered[p]?'importiert abgedeckt':S.done[p]?'freigegeben':S.have[p]?'Entwurf':'noch offen'}"><span>${labels[p]}</span><span class="tree-state">${S.covered[p]?'↳':S.done[p]?'✓':p===S.current?'●':S.have[p]?'○':'·'}</span></button>`;
 let html='';
 if(workspace()==='edit')html=`<div class="group-label">SEQUENZEN</div>${B('sequence','Sequenz 01',{cls:'tree-row',attrs:`aria-pressed="${!S.mediaPreview}"`})}${pool()}`;
 else if(workspace()==='finish'&&!S.mediaOpen)html=`<div class="group-label">MASTER</div>${B('finish-section:review','Endkontrolle',{cls:'tree-row',attrs:`aria-pressed="${S.finishSection==='review'}"`})}${B('finish-section:delivery','Ausgabe',{cls:'tree-row',attrs:`aria-pressed="${S.finishSection==='delivery'}"`})}<div class="library-count">${B('media','Medienpool',{cls:'tree-row'})}</div>`;
 else if(S.mediaOpen)html=B('media',workspace()==='production'?'‹ Workflow':'‹ Master',{cls:'tree-row'})+pool();
 else html=`<div class="workflow-heading">${S.pack==='Music Video'?'Music Video':'Core'}<small>Produktionsworkflow</small></div>${S.pack==='Music Video'?navrow('audio'):''}<div class="group-label">GESCHICHTE</div>${['brief','treatment','script'].map(navrow).join('')}<div class="group-label">SHOTS${S.shots.length?' · '+S.shots.length:''}</div>${['board','plan','refs','review'].map(navrow).join('')}<div class="group-label">GENERIERUNG</div>${navrow('takes')}<div class="library-count">${B('media','Medienpool · '+assets().length,{cls:'tree-row'})}<small>${sketchCount()} Sketches · ${Object.keys(S.takes).length} Shots mit Takes</small></div>`;
 $('#nd-browser').innerHTML=html;$('#nd-browser').classList.toggle('pool-browser',S.mediaOpen||workspace()==='edit');
}
function mediaInspector(){const a=selectedAsset();if(!a)return '';const canTrack=S.view==='audio'&&isEdit()&&!S.track&&a.type==='audio',canSource=S.view==='plan'&&isEdit()&&shot()?.source!=='KI-Video'&&a.type==='video',canSketch=S.view==='board'&&isEdit()&&a.type==='sketch'&&a.shot!==undefined;
 return `<div class="inspector-header"><b>${E(a.name)}</b><small>${mediaTypes[a.type]}</small></div>`+group('Medieninformation',prop('Herkunft',a.origin)+prop('Verwendung',a.type==='sketch'?'Storyboard / Animatic':a.type==='reference'?'Produktionsvorlage':a.type==='video'?'Schnitt / Quellclip':'Projekt-Audio'))+group('Aktionen',B('media-back','Zurück zur Arbeitsfläche',{cls:'control'})+(canTrack?B('media-assign-track','Als Projekttrack zuweisen',{primary:true}):'')+(canSource?B('media-assign-source','Als Shot-Quelle zuweisen',{primary:true}):'')+(canSketch?B('media-assign-sketch','Diesem Moment zuweisen',{primary:true}):'')+(a.shot!==undefined?B('media-locate',a.type==='sketch'?'Im Storyboard zeigen':a.type==='reference'?'In References zeigen':'Bei Video-Takes zeigen',{cls:'control'}):'')+'<small>Sichten verändert keine Shot-Zuweisung.</small>');
}
''' +s[end:]
s=s.replace("let actions='';const p=S.view;", "let actions='';const p=S.view;if(S.mediaPreview&&selectedAsset()){$('#nd-surface-tools').innerHTML=`<strong>Quelle · ${E(selectedAsset().name)}</strong><span class=\"grow\"></span>${B('media-back','Zurück')}`;return;}")
s=s.replace("S.mode!=='animatic'", "S.mode==='board'")
s=s.replace("function boardView(){", "function momentStrip(){return `<div class=\"moment-strip\">${moments().map((m,j)=>`<button data-do=\"moment:${j}\" aria-pressed=\"${j===S.moment}\">${sketchPic(at(),j)}<b>${String.fromCharCode(65+j)} · ${m.time.toFixed(1)} s</b><small>${E(m.label)}</small></button>`).join('')}</div>`;}\nfunction boardView(){")
start=s.index('function boardView(){');end=s.index('function planView()',start)
s=s[:start]+'''function boardView(){if(!S.have.board)return emptyView('board');if(S.mode==='animatic')return `<div class="viewer"><div class="viewer-label"><span>Animatic · Sketches</span><span id="nd-playing-label">Shot ${shot().id} · Moment ${S.moment+1}/${moments().length}</span></div>${sketchPic(at(),S.moment)}<span class="meta">${E(moments()[S.moment]?.label)} · eine durchgehende Einstellung</span></div>`;
 if(S.mode==='moments')return `<div class="canvas-caption"><span>${shot().id} · ${E(shot().name)}</span><span>${moments().length} Sketch-Momente · ${shot().duration.toFixed(1)} s</span></div><div class="moment-viewer">${sketchPic(at(),S.moment)}</div>${momentStrip()}<div class="moment-note">A → B → C zeigt die Handlung innerhalb eines Shots. Kein Schnitt zwischen den Sketches.</div>`;
 return `<div class="canvas-caption"><span>Szene 01 · ${S.shots.length} Shots · ${sketchCount()} Sketches</span><span>${total().toFixed(1)} s · 24 fps</span></div><div class="contact-sheet">${S.shots.map((s,i)=>`<button class="shot-tile" data-shot="${i}" aria-pressed="${S.selected.includes(i)}">${sketchPic(i)}<div class="shot-caption"><b>${s.id}</b><span>${E(s.name)}</span><small>${s.duration.toFixed(1)} s</small></div><div class="shot-note">${moments(i).length>1?moments(i).length+' Sketches · eine Einstellung':i===1?'Rückblende · früher in der Story':E(s.action)}</div></button>`).join('')}</div>`;}
''' +s[end:]
s=s.replace("function canvas(){let html;", "function canvas(){if(S.mediaPreview&&selectedAsset()){$('#nd-canvas').innerHTML=`<div class=\"viewer media-preview\">${assetImage(selectedAsset())}<p>${E(selectedAsset().name)}</p><small>${E(selectedAsset().origin)}</small></div>`;return;}let html;")
s=s.replace("function inspector(){\n const", "function inspector(){\n if(S.mediaPreview&&selectedAsset()){$('#nd-inspector').innerHTML=mediaInspector();return;}\n const")
s=s.replace("if(p==='board')body+=group('Bildquelle',", "if(p==='board'&&S.selected.length===1)body+=group('Sketch-Momente',prop('Innerhalb des Shots',moments().length+' Sketches')+B('mode:moments','Sketches öffnen',{cls:'control'})+B('add-moment','Handlungsmoment hinzufügen',{disabled:!isEdit()||moments().length>=6,cls:'control'})+(S.mode==='moments'?field('Zeit im Shot (s)','momentTime',moments()[S.moment].time,'number',`min=\"0\" max=\"${s.duration-.1}\" step=\"0.1\"`)+field('Handlung','momentLabel',moments()[S.moment].label)+B('sketch-source','Sketch aus Medienpool',{disabled:!isEdit(),cls:'control'})+(at()===4?B('sketch-example','3 Sketches simulieren',{disabled:!isEdit(),cls:'control'}):''):'')+'<small>Momente sind keine Schnitte. Das Animatic nutzt ihre Zeitpunkte innerhalb derselben Shotdauer.</small>');\n if(p==='board')body+=group('Bildquelle',")
s=s.replace("if(p==='finish'&&S.have.finish)body=group", "if(p==='finish'&&S.have.finish)body=group")
s=s.replace("function finishView(){if(!S.have.finish)return emptyView('finish');return", "function finishView(){if(!S.have.finish)return emptyView('finish');if(S.finishSection==='delivery')return `<div class=\"document\"><div class=\"eyebrow\">AUSGABE</div><div class=\"document-heading\">Claude-Mouse.mp4</div><p>1920 × 1080 · 24 fps · H.264</p><p class=\"meta\">${S.finishCheck?'Endkontrolle abgeschlossen. Ausgabe unten freigeben.':'Vor der Ausgabe die Endkontrolle abschließen.'}</p>${B('finish-section:review','Endkontrolle öffnen',{cls:'control'})}</div>`;return")
s=s.replace("const modal=S.modal;if(!modal)", "const modal=S.modal;if(!modal)")
s=s.replace("if(modal==='project'){", "if(modal==='media-import'){title='Medien importieren · Simulation';body='<label for=\"nd-media-kind\">Beispieldatei</label><select id=\"nd-media-kind\"><option value=\"video\">Street-take-01.mov</option><option value=\"audio\">Claude-mouse.wav</option></select><p>Die Datei erscheint im Projektbestand. Track- und Shot-Zuweisungen bleiben unverändert.</p>';actions=B('import-media-file','In Medienpool übernehmen',{primary:true});}\n if(modal==='sketch-example'){title='Sketch-Folge für Shot 1E';body='<p>Hebel greifen → herunterziehen → Maschine läuft an.</p><p>3 günstige Draw-Style-Sketches innerhalb derselben Einstellung. Shot-ID und Gesamtdauer bleiben gleich.</p><small>Vorbereitetes Beispiel · kein Modellaufruf und keine tatsächlichen Kosten.</small>';actions=B('apply-sketch-example','Beispielfolge übernehmen',{primary:true});}\n if(modal==='project'){")
s=s.replace("root.style.setProperty('--nd-left',S.left+'px');", "root.style.setProperty('--nd-left',(S.mediaOpen||workspace()==='edit'?Math.max(S.left,230):S.left)+'px');",1)
s=s.replace("if(n){S.current=S.view=n;S.selected=[0];", "if(n){S.current=S.view=n;S.mediaPreview=false;S.moment=0;S.selected=[0];")
s=s.replace("function position(t){S.position=", "function position(t){const previousMoment=S.moment;S.position=")
s=s.replace("const previous=at();S.selected=[i];if", "const previous=at();S.selected=[i];S.moment=Math.max(0,moments(i).findLastIndex(m=>m.time<=S.position-shotStart(i)));if")
s=s.replace("previous!==i){canvas();inspector();}", "(previous!==i||previousMoment!==S.moment)){canvas();inspector();}")
s=s.replace("function choose(i,multi=false,range=false){stop();", "function choose(i,multi=false,range=false){stop();S.moment=0;S.mediaPreview=false;")
s=s.replace("if(verb==='workspace'){visit(param==='production'?(['edit','finish'].includes(S.current)?'takes':S.current):param);return;}", "if(verb==='workspace'){visit(param==='production'?(S.productionView||(['edit','finish'].includes(S.current)?'takes':S.current)):param);return;}\n if(verb==='asset'){stop();S.mediaSelection=param;S.mediaPreview=true;render();persist();return;}\n if(verb==='moment'){stop();S.moment=+param;S.position=shotStart()+moments()[S.moment].time;canvas();bottom();inspector();persist();return;}\n if(verb==='finish-section'){S.finishSection=param;S.mediaPreview=false;render();persist();return;}")
s=s.replace("surfaceTools();canvas();bottom();persist();return;}", "surfaceTools();canvas();bottom();inspector();persist();return;}",1)
s=s.replace("case'project':case'new':case'import':case'budget':", "case'media':stop();S.mediaOpen=workspace()==='edit'?true:!S.mediaOpen;S.mediaPreview=false;render();persist();break;\n case'media-back':case'sequence':S.mediaPreview=false;render();persist();break;\n case'media-locate':{const a=selectedAsset();if(!a)break;visit(a.type==='sketch'?'board':a.type==='reference'?'refs':'takes');S.mediaOpen=false;choose(a.shot);if(a.type==='sketch'){S.mode='moments';S.moment=a.moment;}else if(a.type==='reference')S.refMode=a.id.startsWith('anchor-')?'anchors':'identities';render();persist();break;}\n case'import-media-file':{const kind=$('#nd-media-kind').value;S.mediaImports.push({id:'import-'+S.mediaImports.length,name:kind==='audio'?'Claude-mouse.wav':'Street-take-01.mov',type:kind,origin:'Importierte Beispieldatei'});S.mediaOpen=true;S.mediaFilter=kind;S.modal=null;render();persist();break;}\n case'media-assign-track':if(isEdit()&&S.view==='audio'&&selectedAsset()?.type==='audio'){S.track=true;S.mediaPreview=false;render();persist();}break;\n case'media-assign-source':if(isEdit()&&S.view==='plan'&&selectedAsset()?.type==='video'){checkpoint();S.selected.forEach(i=>S.shots[i].sourceFile=selectedAsset().name);changed();S.mediaPreview=false;render();persist();}break;\n case'sketch-source':S.mediaOpen=true;S.mediaFilter='sketch';S.mediaPreview=false;render();persist();break;\n case'media-assign-sketch':if(isEdit()&&S.view==='board'&&selectedAsset()?.type==='sketch'){checkpoint();const a=selectedAsset(),source=moments(a.shot)[a.moment];Object.assign(moments()[S.moment],{asset:source.asset,frame:source.frame});changed();S.mediaPreview=false;render();persist();}break;\n case'add-moment':if(isEdit()&&S.view==='board'&&moments().length<6){checkpoint();const ms=moments();let slot=0,gap=0;ms.forEach((m,j)=>{const space=(ms[j+1]?.time??shot().duration)-m.time;if(space>gap){gap=space;slot=j;}});ms.splice(slot+1,0,{time:Math.round((ms[slot].time+gap/2)*100)/100,label:'Neuer Handlungsmoment',asset:null});S.moment=slot+1;S.mode='moments';changed();render();persist();}break;\n case'apply-sketch-example':if(isEdit()&&S.view==='board'&&at()===4){checkpoint();shot().moments=momentExample().map(m=>({...m,time:m.time*shot().duration/5}));S.moment=0;S.modal=null;changed();render();persist();}break;\n case'project':case'new':case'import':case'budget':case'media-import':case'sketch-example':")
s=s.replace("else if(key==='exposure')", "else if(key==='momentTime'){const ms=moments(),j=S.moment;ms[j].time=j===0?0:Math.max(ms[j-1].time+.01,Math.min((ms[j+1]?.time??shot().duration)-.01,+value||0));}\n else if(key==='momentLabel')moments()[S.moment].label=value;\n else if(key==='exposure')")
s=s.replace("S.selected.forEach(i=>S.shots[i][key]=n);", "S.selected.forEach(i=>{if(key==='duration'){const ratio=n/S.shots[i].duration;moments(i).forEach(m=>m.time=Math.round(m.time*ratio*100)/100);}S.shots[i][key]=n;});")
s=s.replace("if(e.target.matches('[data-demo]'))", "if(e.target.matches('[data-media-filter]')){S.mediaFilter=e.target.value;browser();persist();return;}if(e.target.matches('[data-demo]'))")
s=s.replace("if(saved?.schema!==4||", "if(![4,5].includes(saved?.schema)||")
s=s.replace("S={...blank(),...saved,playing:false,running:false,modal:null};", "S={...blank(),...saved,schema:5,playing:false,running:false,modal:null};S.shots.forEach((s,i)=>{s.moments??=i===4?momentExample().map(m=>({...m,time:m.time*s.duration/5})):[{time:0,label:'Einstellung',asset:'base'}];});")
s=s.replace("case'board':return S.have.board&&S.shots.length>0;", "case'board':return S.have.board&&S.shots.length>0&&S.shots.every((s,i)=>moments(i).every(m=>m.asset&&m.time>=0&&m.time<s.duration));")
s=s.replace("if(p==='plan'&&S.shots.some(s=>s.y>0))", "if(p==='board'&&S.have.board&&!readiness())return 'Sketch für einen Handlungsmoment fehlt';\n if(p==='plan'&&S.shots.some(s=>s.y>0))")
p.write_text(s)
p=Path('docs/ui/build-desktop-production-workbench.py');s=p.read_text().replace("('storyboard-sketches.jpg')","('storyboard-sketches.webp')")
s=s.replace("'storyboard-sketches.jpg'", "'storyboard-sketches.webp'").replace("'storyboard-concept.jpg')", "'storyboard-concept.webp'), ('__MOMENTS__', 'shot-1e-moments.webp')").replace("data:image/jpeg;base64,", "data:image/webp;base64,")
p.write_text(s)
