from pathlib import Path
p=Path('docs/ui/desktop-production-workbench.workflow.js');s=p.read_text()
s=s.replace("for(const s of S.shots){S.anchorInputs[s.id]", "for(const s of S.shots.filter(s=>s.source==='KI-Video')){S.anchorInputs[s.id]")
s=s.replace(" for(const [i,takes] of Object.entries(S.takes))", " for(const shot of S.shots.filter(s=>s.source!=='KI-Video')){if(S.anchorInputs[shot.id]){saveAnchor(shot);delete S.anchorInputs[shot.id];delete shot.anchorVariant;}}S.anchorCount=S.shots.filter(s=>s.source==='KI-Video'&&hasAnchor(s.id)).length;\n for(const [i,takes] of Object.entries(S.takes))",1)
s=s.replace("!active.some(b=>b.type==='video'", "!(a.type==='video'&&a.shotID!==undefined&&a.take!==undefined&&active.some(b=>b.type==='video'")
s=s.replace("===a.signature)).map(a=>", "===a.signature))).map(a=>")
s=s.replace("function changeShots(op,target){", "function insertWorldAfter(s){worldShots().forEach((i,n)=>S.shots[i].worldOrder=n*2);return s?s.worldOrder+1:0;}\nfunction changeShots(op,target){")
s=s.replace("if(op==='add'){const id=", "if(op==='add'){const worldOrder=insertWorldAfter(s),id=")
s=s.replace("worldOrder:(s?.worldOrder||0)+.1", "worldOrder")
s=s.replace("newShot.worldOrder=s.worldOrder+.01;", "newShot.worldOrder=insertWorldAfter(s);")
s=s.replace("S.selected.some(i=>(!hasAnchor(S.shots[i].id)||S.clay.staleAnchorIds.includes(S.shots[i].id)))", "!S.selected.some(i=>S.shots[i].source==='KI-Video')||S.selected.some(i=>S.shots[i].source==='KI-Video'&&(!hasAnchor(S.shots[i].id)||S.clay.staleAnchorIds.includes(S.shots[i].id)))")
s=s.replace("${hasAnchor(s.id)?pic(i,'reference'):'<div class=\"take-placeholder\">Anker fehlt</div>'}", "${s.source!=='KI-Video'?takeSource(i).image:hasAnchor(s.id)?pic(i,'reference'):'<div class=\"take-placeholder\">Anker fehlt</div>'}")
s=s.replace("${!hasAnchor(s.id)?'Nicht erzeugt'", "${s.source!=='KI-Video'?'Quellclip · kein Anker nötig':!hasAnchor(s.id)?'Nicht erzeugt'")
s=s.replace("if(hasAnchor(S.shots[i].id)&&", "if(S.shots[i].source==='KI-Video'&&hasAnchor(S.shots[i].id)&&")
s=s.replace("else if(S.referenceCompare){const hasClay", "else if(shot().source!=='KI-Video')$('#nd-canvas').innerHTML='<div class=\"canvas-caption\"><span>'+E(shot().id)+' · Quellclip</span><span>Kein Anker nötig</span></div><div class=\"reference-viewer\">'+takeSource(at()).image+'</div>';else if(S.referenceCompare){const hasClay")
s=s.replace("if(e.target.dataset.wf==='song-offset'){stop();S.songOffset", "if(e.target.dataset.wf==='song-offset'){if(S.view!=='board'||!isEdit())return;stop();checkpoint();S.songOffset")
s=s.replace("Number(e.target.value)||0));bottom();persist();", "Number(e.target.value)||0));changed();bottom();gate();persist();")
s=s.replace("value=\"${start}\" step=\".5\" aria-label=\"Song-Ausschnitt", "value=\"${start}\" step=\".5\" ${isEdit()?'':'disabled'} aria-label=\"Song-Ausschnitt")
p.write_text(s)
p=Path('docs/ui/desktop-production-workbench.clay.js');s=p.read_text().replace("if(!Number.isFinite(v))return;checkpoint();if(k==='include'||k==='travel')", "if(!Number.isFinite(v)&&!['include','travel'].includes(k))return;checkpoint();if(k==='include'||k==='travel')")
p.write_text(s)
