from pathlib import Path
p=Path('docs/ui/desktop-production-workbench.js');s=p.read_text()
s=s.replace("const labels={audio:","const labels={media:'Medien',audio:")
s=s.replace('schema:7','schema:8').replace('version:7,workspace','version:8,workspace').replace('[4,5,6,7].includes','[4,5,6,7,8].includes')
s=s.replace("mediaNextFolder:1,finishSection", "mediaNextFolder:1,mediaReturn:'edit',mediaMarked:[],mediaAIOnly:false,mediaSort:'name',mediaThumb:150,finishSection")
s=s.replace("const workspace=()=>['edit','finish'].includes(S.view)?S.view:'production';", "const workspace=()=>['media','edit','finish'].includes(S.view)?S.view:'production';")
s=s.replace("Schnitt:'edit',Finish:'finish'", "Schnitt:'edit',Medien:'edit',Finish:'finish'")
s=s.replace(" render();\n}\nfunction persist", " if(which==='Medien'){S.view='media';S.mediaOpen=false;S.left=200;S.right=272;S.mediaView='grid';}\n render();\n}\nfunction persist")
s=s.replace("[['production','Produktion'],['edit','Schnitt'],['finish','Finish']]", "[['media','Medien'],['production','Produktion'],['edit','Schnitt'],['finish','Finish']]")
s=s.replace("${p==='production'?!['edit','finish'].includes(S.view):p===S.view}", "${workspace()===p}")
s=s.replace(" if(workspace()==='edit')html=", " if(workspace()==='media')html=libraryNavigation();\n else if(workspace()==='edit')html=")
s=s.replace("const tabs=workspace()==='edit'?'':", "const tabs=['media','edit'].includes(workspace())?'':")
s=s.replace("['media','Medien']].map", "['media','Quellen']].map")
s=s.replace("classList.toggle('pool-browser',S.mediaOpen||workspace()==='edit');", "classList.toggle('pool-browser',workspace()!=='media'&&(S.mediaOpen||workspace()==='edit'));$('#nd-browser').classList.toggle('library-nav',workspace()==='media');")
s=s.replace("function surfaceTools(){\n", "function surfaceTools(){\n if(workspace()==='media'){$('#nd-surface-tools').innerHTML=libraryTools();return;}\n")
s=s.replace("function canvas(){", "function canvas(){if(workspace()==='media'){$('#nd-canvas').innerHTML=libraryCanvas();return;}")
s=s.replace("function inspector(){\n", "function inspector(){\n if(workspace()==='media'){$('#nd-inspector').innerHTML=libraryInspector();return;}\n")
s=s.replace("$('#nd-gate').hidden=S.view==='edit'&&S.have.edit;", "$('#nd-gate').hidden=S.view==='media'||S.view==='edit'&&S.have.edit;")
s=s.replace("['Storyboard','Leer','Audio'", "['Medien','Storyboard','Leer','Audio'")
s=s.replace("function layout(){root.classList.toggle('nle-workspace'", "function layout(){root.classList.toggle('media-workspace',S.view==='media');root.classList.toggle('nle-workspace'")
s=s.replace("'mediaFilter','mediaFolder'", "'mediaMarked','mediaReturn','mediaAIOnly','mediaSort','mediaThumb','mediaFilter','mediaFolder'")
a=s.index(" if(verb==='workspace')");b=s.index(" if(verb==='sidebar')",a)
s=s[:a]+" if(verb==='workspace'){switchWorkspace(param);return;}\n"+s[b:]
a=s.index(" if(verb==='asset')");b=s.index(" if(verb==='moment')",a)
s=s[:a]+" if(verb==='asset'){selectMedia(param);return;}\n"+s[b:]
s=s.replace("if(b.dataset.do){const command=b.dataset.do;action(command);", "if(b.dataset.do){const command=b.dataset.do;if(command.startsWith('asset:'))selectMedia(command.slice(6),e.metaKey||e.ctrlKey,e.shiftKey);else action(command);")
s=s.replace("S.mediaOpen=true;S.mediaQuery='';S.mediaFilter=kind;", "S.mediaOpen=workspace()!=='media';S.mediaQuery='';S.mediaFilter=kind;")
s=s.replace("S.left=340;", "S.left=240;")
s=s.replace("const canTrack=", "const canTrack=")
s=s.replace("+B('pool:move','In Ordner verschieben…',{cls:'control',disabled:S.running})", "+B('pool:reveal','In Medien zeigen',{cls:'control'})")
s=s.replace("if(saved.schema<7&&!saved.mediaFolder)", "if(saved.schema<7&&!saved.mediaFolder)")
s=s.replace("if(S.view==='edit')S.mediaOpen=true;S.shots", "if(saved.schema<8&&S.view==='edit')S.left=240;if(S.view==='edit')S.mediaOpen=true;S.shots")
s=s.replace("fixture('Schnitt');\nif(window", "fixture('Medien');\nif(window")
p.write_text(s)
p=Path('docs/ui/desktop-production-workbench.edit.js');s=p.read_text().replace("B('pool:move','In Ordner verschieben…',{cls:'control',disabled:S.running})", "B('pool:reveal','In Medien zeigen',{cls:'control'})");p.write_text(s)
