from pathlib import Path
p=Path('docs/ui/desktop-production-workbench.test.js');s=p.read_text();needle=" api.fixture('Storyboard');assert('No free chat composer'"
extra=''' api.fixture('Storyboard');
 assert('Workspace switching exists only in titlebar',all('#nd-browser [data-open=edit],#nd-browser [data-open=finish],#nd-browser [data-do^="workspace:"]').length===0);
 api.choose(4);click('mode:moments');assert('One shot contains three distinct sketches',all('.moment-strip .moment-image').length===3&&state().shots.length===6&&state().shots[4].duration===5);
 click('moment:1');assert('Moment selection uses shot-local time',state().selected[0]===4&&state().position===13.8);
 const count=state().shots.length;click('mode:animatic');api.position(12.1);const frameA=q('.viewer .moment-image').style.cssText;api.position(14);const frameB=q('.viewer .moment-image').style.cssText;api.position(16);assert('Animatic advances images without inventing cuts',state().selected[0]===4&&state().moment===2&&frameA!==frameB&&state().shots.length===count);api.position(17.01);assert('Next shot starts at unchanged shot boundary',state().selected[0]===5);
 api.choose(4);click('mode:moments');change('[data-field=duration]',10);assert('Duration edit scales internal moments',state().shots[4].moments[1].time===3.6&&state().shots[4].moments[2].time===7.2);click('undo');
 click('add-moment');assert('New moment stays inside one shot and blocks incomplete board',state().shots.length===6&&state().shots[4].moments.length===4&&!api.readiness());click('undo');assert('Undo restores complete sketch sequence',state().shots[4].moments.length===3&&api.readiness());
 click('sketch-example');click('apply-sketch-example');assert('Sketch generation example preserves shot ID and duration',state().shots[4].id==='1E'&&state().shots[4].duration===5&&state().shots[4].moments.length===3);
 click('workspace:edit');assert('Edit sidebar contains media and sequence, no production phases',!!q('#nd-browser .media-grid')&&!!q('[data-do=sequence]')&&!q('#nd-browser [data-open=board]'));
 click('workspace:finish');assert('Finish has its own review and delivery sidebar',!!q('[data-do="finish-section:review"]')&&!!q('[data-do="finish-section:delivery"]')&&!q('#nd-browser .media-grid'));
 click('workspace:production');assert('Returning to production restores selected shot and local view',state().view==='board'&&state().mode==='moments'&&state().selected[0]===4&&!state().mediaOpen);
 click('media');assert('Production pool leaves central work surface intact',!!q('#nd-browser .media-grid')&&!!q('.moment-viewer')&&state().view==='board');
 const rev=state().version;click('asset:sketch-4-1');assert('Media preview does not change workflow or revision',state().view==='board'&&state().version===rev&&q('.media-preview'));
 click('media-back');click('media');assert('Production workflow returns in same sidebar',!!q('#nd-browser [data-open=board]')&&!q('#nd-browser .media-grid'));
 api.fixture('Leer','Music Video');click('media');click('media-import');change('#nd-media-kind','audio');click('import-media-file');assert('Import populates pool without assigning project track',state().mediaImports.length===1&&!state().track&&!state().audioReady&&state().current==='audio');click('asset:import-0');click('media-assign-track');assert('Track assignment is an explicit media action',state().track&&!state().lyricsChoice&&state().current==='audio');
 api.fixture('Shotplanung');api.choose(2);change('[data-field=source]','Importierter Clip');click('media');click('media-import');change('#nd-media-kind','video');click('import-media-file');click('asset:import-0');assert('Imported source still requires assignment',!state().shots[2].sourceFile&&!api.readiness());click('media-assign-source');assert('Source assignment affects selected shot only',state().shots[2].sourceFile==='Street-take-01.mov'&&!state().shots[0].sourceFile&&api.readiness());
 api.fixture('Schnitt');assert('Edit starts with a usable populated media browser',all('.media-tile').length>0&&!!q('.edit-timeline'));change('[data-media-filter]','video');assert('Video bin excludes sketches',all('.media-tile').length===12&&all('#nd-browser .sketch').length===0);click('asset:take-0-2');assert('Source preview preserves editing timeline and chosen take',!!q('.edit-timeline')&&state().chosen[0]===1&&state().mediaPreview);click('sequence');assert('Sequence returns after source preview',!!q('.edit-viewer')&&!state().mediaPreview);
 api.fixture('Finish');click('finish-section:delivery');assert('Finish delivery view is distinct and gated',q('#nd-canvas').textContent.includes('H.264')&&!api.readiness());click('finish-section:review');assert('Finish review returns to viewer',!!q('#nd-canvas .viewer'));
 api.fixture('Storyboard');const saved=state();saved.schema=4;saved.shots.forEach(s=>delete s.moments);api.restore(saved);assert('Existing saved mockups gain sketch moments safely',state().schema===5&&state().shots[4].moments.length===3);
'''
s=s.replace(needle,extra+needle);p.write_text(s)
