from pathlib import Path
p=Path('docs/ui')
def replace(s,a,b):
 assert a in s,a[:110]
 return s.replace(a,b)
def line(s,start,new):
 ls=s.splitlines(); matches=[i for i,v in enumerate(ls) if v.startswith(start)];assert len(matches)==1,(start,matches);ls[matches[0]]=new;return '\n'.join(ls)+'\n'
f=p/'desktop-production-workbench.js';s=f.read_text()
s=line(s," $('#nd-status').innerHTML=", " $('#nd-status').innerHTML='';")
s=replace(s,"[data-nle-clip],[data-media-drag],[data-library-drag]", "[data-nle-clip],[data-sx-clip],[data-media-drag],[data-library-drag]")
s=replace(s,"const options={columns:'2',height:850};", "const options={columns:'2',height:850,example:S.fixture};let example=options.example;")
s=replace(s,"onChange:()=>{root.style", "onChange:()=>{if(example!==options.example){example=options.example;fixture(example);}root.style")
s=replace(s,"tweak.addSelect(options,'columns'", "tweak.addSelect(options,'example',{label:'Beispielprojekt',options:['Leer','Medien','Audio','Storyboard','Shotplanung','References','Review','Takes','Schnitt','Postproduction','Export']});tweak.addSelect(options,'columns'")
f.write_text(s)
f=p/'desktop-production-workbench.studio.js';s=f.read_text()
s=line(s,"gate=function", """gate=function(){oldGate();if(['edit','post','finish'].includes(S.view))$('#nd-gate').hidden=true;const status=S.view==='media'?poolItems().length+' Medien'+(S.mediaMarked.length?' · '+S.mediaMarked.length+' ausgewählt':''):['edit','post'].includes(S.view)?clipName(nleClip())+' · '+fps()+' fps':S.view==='finish'?finishFormatLabel():labels[S.view];$('#nd-status').innerHTML=`<span class="studio-status-context">${E(status)}</span><span class="grow"></span>${SX('activity',S.running?'Auftrag läuft…':'Aufträge',{cls:'control'})}${B('budget','Budget '+money(S.cost)+' / '+money(S.cap),{disabled:S.running})}${S.view==='finish'?B('finish:export','Exportieren…',{primary:true,disabled:!finishReady()}):''}`;};""")
s=replace(s,"if(time!==null)n.cursor=time;render();", "if(time!==null)n.cursor=time;else if(n.cursor<c.start||n.cursor>=c.start+nleLength(c))n.cursor=c.start;if(c.type==='audio'){n.tab='audio';if(S.view==='post')S.studio.post='audio';}else if(n.tab==='audio')n.tab='video';render();")
s=replace(s,"const tab=S.view==='post'?S.studio.post:S.nle.tab;let body='';", "const tab=S.view==='post'?S.studio.post:S.nle.tab;if(c.type==='audio'&&['video','color','adjust','effects','ai'].includes(tab))return '<div class=\"inspector-header\"><b>'+E(clipName(c))+'</b><small>Audioclip ausgewählt</small></div>'+SX('post-audio','Ton bearbeiten',{cls:'control'});let body='';")
s=replace(s,"['captions','UT']", "['captions','Untertitel']")
s=replace(s,"['ai','KI']].map", "['ai','KI']].filter(([id])=>c.type!=='audio'||['audio','titles','captions'].includes(id)).map")
s=replace(s,"['wheels','Räder']", "['wheels','Farbräder']").replace("['key','Key']","['key','Chroma-Key']")
s=replace(s,"['system-ui','Georgia','monospace']", "[['system-ui','Systemschrift'],['Georgia','Georgia'],['monospace','Monospace']]")
s=replace(s,"['left','center','right']", "[['left','Links'],['center','Zentriert'],['right','Rechts']]")
s=replace(s,"function keyframeControls(c){return", "const keyLabels={opacity:'Deckkraft',scale:'Skalierung',x:'Position X',y:'Position Y',gain:'Lautstärke'};\nfunction keyframeControls(c){const options=Object.entries(keyLabels).filter(([k])=>c.type!=='audio'||k==='gain');if(!options.some(([k])=>k===S.studio.keyParam))S.studio.keyParam=options[0][0];return")
s=replace(s,"['opacity','scale','x','y','gain']", "options")
s=replace(s,"${k.key}", "${keyLabels[k.key]||k.key}")
s=replace(s,"['Linear','Ease In','Ease Out','Ease In/Out','Hold']", "[['Linear','Linear'],['Ease In','Sanft beginnen'],['Ease Out','Sanft enden'],['Ease In/Out','Sanft beginnen / enden'],['Hold','Konstant']]")
s=replace(s,"sxSelect('Pattern'", "sxSelect('Erzählmuster'").replace('Zustandsleiter','Zustandsverlauf').replace('Quellbindung prüfen','Quellen prüfen')
s=line(s,"poolItems=function", """const visualTags=['Straße Staub Morgen','Maus Zahnrad','Katze Veranda','Geschenk Hände','Maschine Motor','Stadt Abend'];
function searchHits(a){const query=S.mediaQuery.trim().toLocaleLowerCase('de');if(!S.studio.index||a.offline)return [];const segments=S.studio.search==='spoken'?(['audio','video'].includes(a.type)?a.transcript||[]:[]):['video','image','reference','sketch'].includes(a.type)?a.visualSegments||[{text:visualTags[a.shot??a.demoPic]||''}]:[];return segments.filter(x=>x.text.toLocaleLowerCase('de').includes(query));}
poolItems=function(){if(S.studio.search==='files'||!S.mediaQuery.trim())return oldPoolItems();const query=S.mediaQuery;S.mediaQuery='';let list;try{list=oldPoolItems();}finally{S.mediaQuery=query;}return list.filter(a=>searchHits(a).length);};""")
s=line(s,"poolResults=function", """poolResults=function(){return oldPoolResults().replace(/draggable="[^"]*" data-media-drag="[^"]*"/g,'').replace(/data-do="asset:([^"]+)"/g,(m,id)=>{const a=assets().find(x=>x.id===id);return m+(workspace()==='edit'&&a?.type!=='text'?` draggable="true" data-media-drag="${id}"`:'');})+(S.mediaQuery&&S.studio.search!=='files'?`<div class="studio-search-detail"><small>${S.studio.search==='spoken'?'Transkript':'Bildinhalt'} · ${S.studio.index?'Indexierte Beispielinhalte':'Suchindex pausiert'}</small>${poolItems().flatMap(a=>searchHits(a).map((hit,i)=>SX('moment-'+a.id+'~'+i,`${E(a.name)}${Number.isFinite(hit.in)?' · '+tc(hit.in)+'–'+tc(hit.out):''} · ${E(hit.text)}`,{cls:'control'}))).join('')}</div>`:'');};""")
s=replace(s,"['files','Dateien']", "['files','Dateiname']").replace("['spoken','Gesprochenes']", "['spoken','Transkript']")
s=line(s," if(command.startsWith('moment-'))", " if(command.startsWith('moment-')){const [id,index]=command.slice(7).split('~'),a=assets().find(x=>x.id===id),hit=a&&searchHits(a)[+index];if(!hit)return;S.mediaSelection=id;S.mediaMarked=[id];t.sourceIn=hit.in||0;t.sourceOut=hit.out||assetDuration(a)||5;S.mediaPreview=S.view!=='media';render();return;}")
s=replace(s,"SX('asset-relink','Neu verknüpfen…',{cls:'control'})", "SX('asset-relink','Neu verknüpfen…',{cls:'control',disabled:!a.offline})")
s=replace(s,"SX('asset-generate','Mit diesen Vorgaben generieren…',{cls:'control'})", "(a.generation?SX('asset-generate','Mit diesen Vorgaben generieren…',{cls:'control'}):'')")
s=replace(s,"+SXI('source-close','x','Quelltab schließen');", "+(S.mediaPreview?SXI('source-close','x','Quelltab schließen'):'');")
# Do not pretend the text-to-video endpoint accepts video or image conditioning.
s=replace(s,"flex=m.id.includes('seedance')", "flex=!!m.conditioning")
s=replace(s,"if(S.studio&&!m.id.includes('seedance'))", "if(S.studio&&!m.conditioning)") if "if(S.studio&&!m.id.includes('seedance'))" in s else s
f.write_text(s)
f=p/'desktop-production-workbench.media.js';s=f.read_text()
s=line(s,"function mediaSearchControl()", "function mediaSearchControl(){const label={files:'Dateinamen suchen',moments:'Bildinhalt suchen',spoken:'Transkript durchsuchen'}[S.studio?.search||'files'];return `<label class=\"pool-search\">${MI('search')}<input type=\"search\" data-media-search aria-label=\"${label}\" placeholder=\"${label}\" value=\"${E(S.mediaQuery)}\"></label>`;}")
s=replace(s,"$('.pool-foot').textContent=poolItems().length+' Medien';", "$('.pool-foot').textContent=poolItems().length+' Medien';gate();")
f.write_text(s)
f=p/'desktop-production-workbench.generate.js';s=f.read_text().replace("!m.id.includes('seedance')", "!m.conditioning");f.write_text(s)
f=p/'desktop-production-workbench.finish.js';s=f.read_text()
s=replace(s,"const finishHasCut", "const finishAudioTracks=()=>S.nle?.tracks.filter(t=>t.type==='audio')||[];\nconst finishHasCut")
s=replace(s,"prop('A1',S.nle?.muted?'Stumm':'Aktiv')+prop('Pegel',(S.nle?.gain||0)+' dB')", "finishAudioTracks().map(t=>prop(t.id,t.hidden?'Stumm':S.nle.clips.some(c=>c.track===t.id)?'Aktiv':'Leer')).join('')")
s=replace(s,"if(S.nle.muted)", "if(finishAudioTracks().some(t=>t.hidden&&S.nle.clips.some(c=>c.track===t.id)))")
s=replace(s,"detail:'A1 ist stummgeschaltet.", "detail:'Eine belegte Tonspur ist stummgeschaltet.")
s=replace(s,"size:finishSize(),duration:nleTotal()", "size:finishSize(),fps:fps(),duration:nleTotal()")
s=replace(s,"prop('Bildgröße',x.size.join(' × '))+prop('Bildrate',fps()+' fps')", "prop('Bildgröße',x.size.join(' × '))+prop('Bildrate',(x.fps||'Unbekannt')+' fps')")
f.write_text(s)
