from pathlib import Path
import csv
root=Path('docs/ui');f=root/'review/native-ui-capabilities.tsv';rows=list(csv.DictReader(f.open(),delimiter='\t'))
prior=root/'review/native-ui-capabilities-before-studio.tsv'
if not prior.exists(): prior.write_text(f.read_text())
notes={
'APP-01':'Projektmenü: Neu, Öffnen, Sichern, Kopie; Sitzungsstand wiederherstellbar. Keine echten Dokumentdateien.',
'APP-02':'Projektmenü > Letzte Projekte, Verlauf entfernen; Dateiort im Medien-Inspector. Native Finder-/Papierkorboperationen bleiben Systemadapter.',
'APP-03':'Projektmenü > Projekteinstellungen: Name, Format, Auflösung, FPS gemeinsam in Viewer, Timeline und Export.',
'APP-04':'Schnitt, Postproduction und Export frei erreichbar; leeres Generic-Projekt mit Fremdmedien bis zur Ausgabe geprüft.',
'APP-05':'Unabhängige Sidebar-Icons, Splitter und gespeicherter Layoutzustand; 320–1440 px geprüft.',
'APP-06':'Projekt > Fenster & Ansichten, Viewer maximieren, Vollbild, zwei Layouts. Browser-Vollbild hängt von Host-Erlaubnis ab.',
'APP-07':'Undo/Redo, Clip-Clipboard, Duplizieren, Mehrfachauswahl, Löschen und Tastatur im Schnitt. Kein nativer macOS-Responder-Test.',
'APP-08':'Projekt > Hilfe & Tastatur: Einführung, lokaler Feedbackentwurf, Update-Simulation. Kein Versand und kein echter Updater.',
'APP-09':'Statusleiste > Aufträge und Projekt > Aufträge & Entscheidungen: Revisions-/Zeit-/Ergebnisverlauf.',
'APP-10':'Gemeinsame dunkle Controls, Fokus, deutlich deaktivierte Aktionen, Pack-Flächen. HTML ist kein Ersatz für native AppTheme-Primitives.',
'MED-01':'Medien > Import: Video, Bild, Audio, Text, Lottie; leerer Schnitt > fünf Beispielquellen. Dateiauswahl bleibt Simulation.',
'MED-02':'Ordnerbaum: Unterordner, Umbenennen, Verschieben, Entfernen; Inhalte beim Entfernen nach Importe übernehmen.',
'MED-03':'Datei-Inspector: Name, Auswahl entfernen, Beispielpfad, Offline-/Relink-Fall; Timeline-Instanzen bleiben bestehen.',
'MED-04':'Medien: Cmd-/Shift-Auswahl und aufgezogener Auswahlbereich, gemeinsame Mehrfachaktionen.',
'MED-05':'Typ-/KI-Filter, Sortierung, Raster/Liste, Größe und Ziehen; nativen AppKit-Drop-Host später unverändert einbinden.',
'MED-06':'Medien > Bildinhalt: Beispieltreffer mit Zeitsegment, Quellbereich übernehmen. Kein echter visueller Index.',
'MED-07':'Medien > Gesprochenes: Beispieltreffer mit Quellzeit. Kein lokales Sprachmodell im HTML.',
'MED-08':'Suchstatus und Einstellungen > Speicher: Index aktivieren/neu aufbauen. Download-/Indexrunner bleibt nativer Adapter.',
'MED-09':'Dateiaktionen > Offline-Fall und Relink Einzeldatei/Ordner. IDs und Timeline-Instanzen bleiben erhalten.',
'MED-10':'Datei-/Quellen-Inspector zeigt Herkunft, Modell, Intention, Kosten und Referenz-ID erzeugter Demo-Assets.',
'MED-11':'Ein gemeinsamer Bestand für Medien, Quellen-Picker und Timeline; In Medien zeigen bleibt kontexttreu.',
'MED-12':'Text bleibt Quelldokument. Video, Audio, Bild und Lottie sind unabhängig von Shots einsetzbar.',
'MED-13':'Medien > Organisieren: Vorschlag, begrenzte Annahme, bestehende Ordnerzuordnung und Undo.',
'GEN-01':'Medien > Generieren: Typ, Intention, Provider/Modell, vorbereiteter Auftrag, Kosten und Ergebnis. Kein Content-Modell aufgerufen.',
'GEN-02':'Provider-/Modellschalter filtern die Generatorauswahl; leere ausführbare Menge deaktiviert Vorbereitung. Demokatalog, keine Live-Verfügbarkeit.',
'GEN-03':'Generator > Eingaben: Demo-Fähigkeitsprofil, Endbild/Referenz oder Quellvideo exklusiv; Quellen an Freigabe gebunden. Native Rollen-/Limitvalidatoren bleiben maßgeblich.',
'GEN-04':'KI-Bearbeitung am Clip sowie Generator-Quellvideo/Trim; tatsächliche Videoextraktion ist nicht verbunden.',
'GEN-05':'Audio-Demoprofile für Sprache/Musik: Stimme, Lyrics/Stil, Instrumental und Dauer. Keine verifizierte Providerpreisliste.',
'GEN-06':'Auftrag und Beispielkosten vor Annahme, Revision und gebundene Quellen erneut geprüft; Rückkehr verwirft Quote.',
'GEN-07':'Video-Takes vorbereiten: Einträge entfernen, Gesamtkosten bestätigen; leere Auswahl sperrt Annahme.',
'GEN-08':'Batch: fertige Ergebnisse behalten, Rest stoppen, fortsetzen; gespeicherter laufender Auftrag öffnet pausiert. Keine echte Provider-Reconciliation.',
'GEN-09':'Clip > KI: bearbeiten, hochskalieren, mit Vorgaben erneut erzeugen; neues Medium oder bewusster Instanzersatz.',
'GEN-10':'Clip/Ton > Video zu Musik oder SFX: begrenzter Quellauftrag, Ergebnis in gemeinsamen Medien, danach frei einsetzbar.',
'GEN-11':'Ton > Musik erzeugen: Richtung als strukturierte Auswahl und optionale Präzisierung; zusätzlich manuelles Audio-Musikprofil.',
'NLE-01':'Freie Montage aller platzierbaren Medientypen in leerem Generic-Projekt bis Export geprüft.',
'NLE-02':'Gemeinsame Mehrspur-Timeline, Spuren hinzufügen/entfernen, Bild-/Audio-/Titelspuren, Sperren und Sichtbarkeit.',
'NLE-03':'Clip- und Marquee-Mehrfachauswahl, Clipboard, Duplizieren, Ziehen und Option-Duplizieren.',
'NLE-04':'Rasierklinge, Split, Kanten-Trim, Löschen/Ripple/Lücken schließen. Gesperrte Spuren bleiben gesperrt; native RippleEngine weiterverwenden.',
'NLE-05':'Quelle In/Out, Insert und Overwrite; Segment-Drops in typkompatible Spuren. Native Randfallsemantik nicht durch HTML ersetzen.',
'NLE-06':'Timeline-Zoom, Einrasten, Auto-Scroll und Timeline-Höhe. Individuelle native Spurhöhen bleiben Integrationsdetail.',
'NLE-07':'Clip-Menü > Verbinden/Trennen; Spurkopf > Sync-Lock, Sperre und Sichtbarkeit/Stumm. Linking getrennt von Sync-Lock.',
'NLE-08':'Clip-Menü > Sequenzbereich mit In/Out und Als Medium sichern.',
'NLE-09':'Clip-Inspector/-Menü: Quelle austauschen und Als Medium sichern; eigene Asset-ID.',
'NLE-10':'Clip-/Ton-Auftrag > Audio synchronisieren: Beispielversatz vorschlagen und auf ungesperrte Audiospur anwenden.',
'VIEW-01':'Quellen-Tabs, Timeline-Rückkehr und Schließen; gemeinsamer Bestand. Nativer vollständiger Tab-Verlauf bleibt zu binden.',
'VIEW-02':'Transport, Scrub, FPS-genaue Schritte, Vorschauzoom/Fit. Standbildanimation ohne Videodecoder/Ton.',
'VIEW-03':'Kamera-Aktion im Viewer erzeugt ein neues Beispielbild im Medienbestand.',
'VIEW-04':'Offline-Bild statt erfolgreichem Schwarzbild, Relink und laufende Auftragsansicht.',
'POST-01':'Video-Inspector: Position, Scale, Rotation, Deckkraft, Flip, Beschnitt und optionale direkte Bildpositionierung.',
'POST-02':'Clip-In/Out und Tempo auf derselben Instanz; native Retiming-/Audio-Semantik bleibt für Produktintegration verbindlich.',
'POST-03':'Keyframe-Gruppe: Parameter, Setzen, Auswahl/Sprung, Zeit/Wert bearbeiten, Löschen.',
'POST-04':'Linear, Ease In/Out und Hold; Transform/Deckkraft in Vorschau interpoliert. Effekt-/Audioautomation nutzt später native Renderer.',
'POST-05':'Farbe > Basis: alle Tonwert-/WB-/Vibrance-/Sättigungsparameter, Bypass, Reset, Undo. Vorschau vereinfacht.',
'POST-06':'Farbe > Kurven: RGB, Einzelkanäle und Hue-Ziele, fünf editierbare Punkte mit Diagramm. Keine native Farbpipeline im Browser.',
'POST-07':'Farbe > Räder: Schatten/Mitten/Lichter mit Farbton, Stärke und Helligkeit; gemeinsame Clipdaten.',
'POST-08':'Farbe > LUT: Auswahl, Beispielimport, Intensität und Bypass; echte .cube-Auswertung bleibt nativ.',
'POST-09':'Farbe > Effekte: Schärfe, Denoise, Clarity, Dehaze als gespeicherte Parameter; kein nachgebauter Bildrenderer.',
'POST-10':'Effekte: Blur, Motion Blur und Winkel; vereinfachte Blur-Vorschau.',
'POST-11':'Effekte: Vignette, Grain, Glow mit Teilparametern. Browser zeigt nur vereinfachte Wirkung.',
'POST-12':'Farbe > Key: Farbton, Toleranz, Softness, Spill gespeichert; native Chroma-Komposition ist nicht simuliert.',
'POST-13':'Farbe > An Referenz angleichen: begrenzter Beispielvorschlag mit Annahme/Undo; kein erfundenes natives Scope-Panel.',
'POST-14':'Ton: Clip-Pegel, Fade-in/out, Tempo und Gain-Keyframes. Ohne Audioausgabe im Clickdummy.',
'POST-15':'Titel: mehrere Instanzen, Text, Schrift, Größe, Farbe, Hintergrund, Kontur, Schatten, Layout, Timing und Löschen.',
'POST-16':'Untertitel: Quelle, Sprache, Stil, Filter, Beispieltranskription; Ergebnis sind editierbare Titelclips.',
'POST-17':'Untertitel-Aufträge: Korrektur, Übersetzung und Füllwort-/Schnittvorschlag mit Annahme. Beispieltext statt Transkript-Engine.',
'PROD-01':'Getrennte Core-Zielphasen und Pack-Beiträge; Generic/Music Video, fehlender/unbekannter Pack sperrt UI. Zielreihenfolge bleibt Vorschlag NEW-03, kein nativer Vertragsersatz.',
'PROD-02':'Musicvideo-Start, explizite Medienzuweisung, optionale Lyrics; Material-Intake erst nach Audioanalyse.',
'PROD-03':'Wiederholbares Material-Intake mit Nummer, Art/Name/Bild, Pflichtfeldsperre, Überspringen/Fertig.',
'PROD-04':'Audio: Wellenform, Sektionen, Energie/Spannung und Interpretation; Drilldown bis Takt. Werte sind Demo-Evidenz.',
'PROD-05':'Analyse-Inspector: Messdetails und erneuter Messauftrag. Keine lokale Audioanalyse im HTML.',
'PROD-06':'Brief, Gestaltung, Treatment, Skript und Storyboard mit eigenen Aufgaben; native Artefakt-/Writer-Trennung dokumentiert.',
'PROD-07':'Brief/Treatment: Pattern-Empfehlung, Alternativen und Begründung. Kein nachgerechneter nativer Fit-Score.',
'PROD-08':'References > Identitäten: Figuren, Ensembles, Props, Orte und Look; gerenderte Beispielreferenzen.',
'PROD-09':'Objekt-Inspector: Verwendung und direkter Shot-Sprung; Medien/Take/Clip beziehen sich auf gemeinsame IDs. Graph exemplarisch.',
'PROD-10':'Entity-Inspector: Attribute, Sperren, Herkunft und begrenzter Änderungsauftrag; Ankerfreigaben werden revidiert.',
'PROD-11':'Shotplanung: generiert/importiert/AI-enhanced und explizite Quellwahl; echte Dateivalidierung bleibt nativer Writer.',
'PROD-12':'Shotplanung: Dauer/Kamera, Conditioning, Modell/Profil und Quellbindungsprüfung. Native Modell-Limits weiterverwenden.',
'PROD-13':'Shot-Inspector: Anschlussstrategie und Quellbindungen für Frame-Continuation/native Extension.',
'PROD-14':'Blocking: gemeinsamer Plan, Blockout und 360°-POV-Auftrag; keine separate 3D-Modellierungs-App.',
'PROD-15':'Render-Review: Story-Weltzeit und Zustandsanschlüsse statt reiner Montagefolge; demonstrierter Kausalitätskonflikt.',
'PROD-16':'Render-Review > Befunde/Evidenz, Schwere und Korrekturwege; vorhandene native CheckRegistry ist später anzubinden.',
'PROD-17':'References > Anker: Auswahl, Neuversuch und Remix als geprüfter Kostenauftrag; Sketches bleiben getrennt.',
'PROD-18':'Bild-/Stilreview an References und Film-/Übergangsreview in Postproduction; exakte Sequenzbindung erkennt Änderungen.',
'PROD-19':'Take-Klick öffnet sechs Prüfgänge. Freigabe/Ablehnung/Abweichung, Pflichtbegründung und aktuelle Revision geprüft.',
'PROD-20':'Takes > Bereich retten: In/Out, Sichtungsbestätigung, Tonwahl, neues Bereichsmedium für gezielten Insert.',
'PROD-21':'Takes > Nächsten Versuch planen: begrenzte Reparatur, Vereinfachung oder Rewind. Kein autonomer Dauerrender.',
'PROD-22':'Vorhandene Demo-Freigabe/Rewind/Revision und aktueller Schritt; laufende Aufträge sperren Eingriffe. Native strukturelle Gates nicht ersetzt.',
'PROD-23':'Takes > Geprüfte Auswahl übernehmen: neue Montage-Spur, vorhandene Sequenz bleibt erhalten; Songbezug.',
'PROD-24':'Shotplanung > Blocking: Plan-/Elevations-Blockout mit Zeitregler oder Importauftrag. Statische Vorschau, kein echter MOV-Export.',
'PROD-25':'Musicvideo ergänzt Shotplanung um Performance-Segmente, Visual Arc/Coverage; Ton nutzt gemeinsamen Song-Clip.',
'PROD-26':'Shotplanung: Video-/Still-Delivery und Ken-Burns-Parameter. Videorender-Engine nicht verbunden.',
'AGENT-01':'Kontextauftrag mit Choice/Multi-choice, Defaults, optionaler Prosa, Pflichtfeldern und Abbruch; kein freier Chat.',
'AGENT-02':'Artefakte/Medien in Arbeitsflächen, Vorschau/Annahme im Interaktionsbereich; native Block-Vokabel nicht als Chat darstellen.',
'AGENT-03':'Beständiger Auftragsbereich, Fortschritt, Stop/Fortsetzen, Backend-Bereitschaft. Provider-Transportfehler bleiben echte Integrationszustände.',
'AGENT-04':'Aufträge binden Clip/Objekt/Revision und Filmstand; kein verdeckter neuer freier Chat.',
'AGENT-05':'Aufträge & Entscheidungen als Verlauf; erneutes Öffnen. Bestehende Chatarchive erfordern bei nativer Migration Erhalt.',
'AGENT-06':'Einstellungen > Agent: Embedded/API-Wahl, Bereitschaft und Verbindungen; keine Geheimnisse im Dummy.',
'AGENT-07':'Einstellungen > Agent: MCP hinzufügen mit explizitem Vertrauen, entfernen. Keine tatsächliche Verbindung.',
'FIN-01':'Postproduction > Endkontrolle: Film, Übergänge, eigene Befunde, Sichtung und Korrekturziel.',
'FIN-02':'Eigener Postproduction-Bereich mit denselben Clips, Grades, Ton und Titeln; Review bindet Bild, Ton, Spuren und Geometrie.',
'FIN-03':'Eigener Export-Bereich: Codec, Master/Ableitung, Auflösung, optionale aktuelle Sichtung; Projekt-FPS/Aspekt und freier NLE-Export.',
'FIN-04':'Export > XML oder Projektkopie, Grenzen ausdrücklich angezeigt; keine tatsächlichen Dateien geschrieben.',
'FIN-05':'Ausgabeauftrag, Fortschritt, Stop und Verlauf. Datei-Prüfung ausdrücklich simuliert, frühere Snapshots unverändert.',
'SET-01':'Einstellungen > Allgemein: Skalierung, Benachrichtigungen, Diagnose-Einwilligung; keine echte Telemetrie.',
'SET-02':'Einstellungen > Provider: simulierte Aktivierung, Generatorfilter; Prompt-Aufbereitung immer aktiv; keine API-Key-Eingabe im Demo.',
'SET-03':'Einstellungen > Modelle: aktivieren/deaktivieren und begrenzter Evidenzvorschlag. Kein live recherchierter Katalog.',
'SET-04':'Einstellungen > Speicher: Speicherort, Cachezustand, Index und Neuaufbau; Originalmedien bleiben erhalten.',
'PACK-01':'Einstellungen > Format-Packs: Projektversion, Update, ungenutzte Version entfernen; Update ändert Projekt nicht still.',
'PACK-02':'Fehlende Version als blockierende Ansicht, passende Version wiederherstellen oder explizite Recovery-Kopie.',
'PACK-03':'Aufgelöste Demo-Packfarbe in Chrome/Selektion/Primäraktionen; generische Phasen plus kleine Pack-Ergänzung. Kein neuer nativer Pack-ABI.',
'CORE-01':'Writer-/Gate-/Lineage-Zuordnung im Erhaltungsvertrag; UI simuliert Freigaben, native Dienste bleiben maßgeblich.',
'CORE-02':'Ein aktiver Demo-Auftrag, laufende Mutationen gesperrt, Batch-Fortsetzung ohne doppelte Ergebnisse; keine MCP-Lifetime-Implementierung.',
'CORE-03':'Kosten-/Quellen-/Revisionsbindung und erneute Prüfung vor Übernahme. Promptcompiler/PreparedRequest später direkt weiterverwenden.',
'CORE-04':'Produktionsprofil am Shot-Inspector mit Pack-Ergänzung; Produktionswissen kommt nativ aus bestehenden Loadern, nicht aus HTML-Prompts.',
'CORE-05':'Analyse-Messdetails benennen lokale Adapter und erneutes Messen; keine Audioadapter oder Stem-DAW im Clickdummy implementiert.',
}
for r in rows:
 if r['id'].startswith('NEW-'): continue
 assert r['id'] in notes,r['id']
 r['mock_status']='simulated';r['mock_observation']=notes[r['id']]
with f.open('w') as o:
 w=csv.DictWriter(o,fieldnames=rows[0].keys(),delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(rows)
p=root/'audit-native-ui.py';s=p.read_text().replace("STATUS = {", "STATUS = {\n    'simulated': 'Im Clickdummy abgebildet (Simulation)',");s=s.replace('„Im Dummy illustriert“ bedeutet ausdrücklich keine native Implementierungsgleichheit.', '„Im Clickdummy abgebildet“ bezeichnet erreichbare Beispieloberflächen und Zustandsmodelle, keine native Implementierungsgleichheit. Die jeweilige Beobachtung nennt Simulationsgrenzen.');p.write_text(s)
p=root/'desktop-production-workbench.spec.html';s=p.read_text();a=s.index('<p><strong>');b=s.index('\n<p>Vorschlag',a);s=s[:a]+'<p><strong>Überarbeiteter Clickdummy mit getrennten Arbeitsbereichen.</strong> Der <a href="review/studio-workspace-review-2026-09-18.md">aktuelle Review</a> dokumentiert umgesetzte Oberflächen, Interaktionsprüfungen und Simulationsgrenzen. Die <a href="review/native-ui-function-matrix-2026-09-18.md">119 Funktionsgruppen</a> bleiben der verbindliche Abgleich zur nativen Implementierung; HTML-Parameter und Beispielergebnisse beweisen keine Engine-Parität.</p>'+s[b:];s=s.replace('Der aktuelle Clickdummy zeigt diese Trennung noch nicht.','Die Trennung ist im Clickdummy umgesetzt.').replace('Der bisherige Finish-Dummy ist nur die Vorgängersimulation und bildet diese Trennung noch nicht ab.','Die Endkontrolle liegt in Postproduction; die Ausgabe ist getrennt.').replace('Konzept, Quellen und offene Funktionslücken','Konzept, Code-Abgleich und Review').replace('Bisherige Finish-Simulation (wird im Zielkonzept durch getrennte Postproduction und Export ersetzt)','Historischer Review der inzwischen ersetzten Finish-Simulation');p.write_text(s)
p=root/'UI_PARITY_CONTRACT.md';s=p.read_text().replace('Der aktuelle Clickdummy ist **keine vollständige Umsetzungsvorlage**.','Der überarbeitete Clickdummy bildet die Arbeitsbereiche und Funktionsgruppen als Simulation ab; [Review und Grenzen](review/studio-workspace-review-2026-09-18.md) sind Bestandteil der Umsetzungsvorlage. Er ist **kein Ersatz für native Funktionsabnahme**.').replace('Die Trennung ist im bestehenden Clickdummy noch nicht umgesetzt.','Die Trennung ist im Clickdummy umgesetzt und interaktiv geprüft.').replace('Ein visuelles und interaktives Review der späteren getrennten Flächen bleibt vor ihrer Präsentation erforderlich.','Die getrennten Flächen wurden visuell und interaktiv geprüft; erneute native Abnahme bleibt vor Ablösung bestehender UI erforderlich.');p.write_text(s)
p=root/'review/native-ui-audit-2026-09-18.md';s=p.read_text();s=s.replace('\n', '\n\n**Historischer Ausgangsbefund vor der Überarbeitung.** Den aktuellen Stand dokumentieren [Studio-Review](studio-workspace-review-2026-09-18.md) und aktualisierte Funktionsmatrix. Die folgenden Lückenzahlen beziehen sich auf den Vorgänger.\n',1);p.write_text(s)
