from pathlib import Path
p=Path('docs/ui/desktop-production-workbench.workflow.js')
s=p.read_text()
s=s.replace('S.takeInputs??={};','S.takeInputs??={};S.takeCounters??={};')
s=s.replace("s.scene??='Straße & Veranda';", "s.scene??='Straße & Veranda';s.stateIn??=s.id==='1E'?(S.reviewFixed?'Repariert, still':'Läuft'):s.id==='1F'?'Läuft':'Defekt';s.stateOut??=s.id==='1D'?'Repariert, still':['1E','1F'].includes(s.id)?'Läuft':s.stateIn;")
s=s.replace("if(s)for(const t of takes)S.takeInputs[s.id+'~'+t]??=takeInput(s);", "if(s)for(const t of takes){S.takeInputs[s.id+'~'+t]??=takeInput(s);S.takeCounters[s.id]=Math.max(S.takeCounters[s.id]||0,t);}")
s=s.replace(" if(S.clay){", " for(const a of S.archive)if(a.take)S.takeCounters[a.shotID]=Math.max(S.takeCounters[a.shotID]||0,a.take);\n if(S.clay){",1)
s=s.replace('s.id,s.action,s.duration,s.camera','s.id,s.action,s.stateIn,s.stateOut,s.camera')
s=s.replace('clayFingerprint(s.id):null','JSON.stringify([clayScene(s.id)?.objects,clayCamera(s.id),S.studio?.aspect]):null')
s=s.replace('[anchorInput(s),S.anchorVersions','[anchorInput(s),s.duration,S.studio?.fps,S.anchorVersions')
pos=s.index('function archiveTakes')
s=s[:pos]+"function hasAnchor(id){return !!S.anchorInputs?.[id];}\nfunction nextTake(i){const s=S.shots[i],n=(S.takeCounters[s.id]||0)+1;S.takeCounters[s.id]=n;S.takeInputs[s.id+'~'+n]=takeInput(s);return n;}\n"+s[pos:]
s=s.replace("type:'video',duration:s.duration", "type:'video',review:clone(S.studio.takeReviews[i+'-'+t]||null),duration:s.duration")
s=s.replace("function compatibleTakes(){return S.archive.filter(a=>a.type==='video'&&S.shots.some(s=>s.id===a.shotID&&a.signature===takeInput(s)));}","function compatibleTakes(){return S.archive.filter(a=>a.type==='video'&&S.shots.some((s,i)=>s.id===a.shotID&&a.signature===takeInput(s)&&!S.takes[i]?.includes(a.take)));}")
s=s.replace("S.takeInputs[a.shotID+'~'+a.take]=a.signature;", "S.takeInputs[a.shotID+'~'+a.take]=a.signature;if(a.review)S.studio.takeReviews[i+'-'+a.take]=clone(a.review);")
s=s.replace('const active=workflowBase.assets();','const active=workflowBase.assets().filter(a=>!a.id.startsWith(\'anchor-\')||hasAnchor(S.shots[a.shot]?.id));')
s=s.replace("S.modal=null;S.running=true;S.completed=0;bgStart('Shot-Anker'", "S.modal=null;undo=[];redo=[];S.running=true;S.completed=0;bgStart('Shot-Anker'")
s=s.replace("S.studio.takeReviews={};", "S.studio.takeReviews=Object.fromEntries(Object.entries(S.studio.takeReviews).filter(([k])=>map[k.split('-')[0]]>=0).map(([k,v])=>[map[k.split('-')[0]]+'-'+k.split('-')[1],v]));for(const id of Object.keys(S.clay.cameras))if(!S.shots.some(s=>s.id===id)){delete S.clay.cameras[id];delete S.clay.outputs[id];}")
s=s.replace("art:0,worldOrder:", "art:0,stateIn:s?.stateOut||'Defekt',stateOut:s?.stateOut||'Defekt',worldOrder:")
s=s.replace("newShot.duration=s.duration-cut;newShot.worldOrder", "newShot.duration=s.duration-cut;splitClay(s,newShot,cut/s.duration);newShot.stateIn=s.stateIn;s.stateOut=s.stateIn;newShot.worldOrder")
s=s.replace("if(S.view==='takes'&&compatibleTakes().length&&!Object.keys(S.takes).length)","if(S.view==='takes'&&compatibleTakes().length)")
s=s.replace('frühere Takes passen zu den aktuellen Eingaben','frühere Takes passen · Demo-Abgleich')
s=s.replace('S.clay.staleAnchorIds.includes(S.shots[i].id))','(!hasAnchor(S.shots[i].id)||S.clay.staleAnchorIds.includes(S.shots[i].id)))')
s=s.replace("${pic(i,'reference')}<b>${E(s.id+' · '+s.name)}</b><small>${S.clay.staleAnchorIds.includes(s.id)","${hasAnchor(s.id)?pic(i,'reference'):'<div class=\"take-placeholder\">Anker fehlt</div>'}<b>${E(s.id+' · '+s.name)}</b><small>${!hasAnchor(s.id)?'Nicht erzeugt':S.clay.staleAnchorIds.includes(s.id)")
s=s.replace("${pic(at(),'reference')}<figcaption>Shot-Anker", "${hasAnchor(shot().id)?pic(at(),'reference'):'<div class=\"take-placeholder\">Anker fehlt</div>'}<figcaption>Shot-Anker")
s=s.replace("if(!S.clay.staleAnchorIds.includes(S.shots[i].id)&&!S.anchorAccepted.includes(i))", "if(hasAnchor(S.shots[i].id)&&!S.clay.staleAnchorIds.includes(S.shots[i].id)&&!S.anchorAccepted.includes(i))")
s=s.replace("if(cmd.startsWith('take-')&&/^take-\\d+$/.test(cmd)){S.studio.takeFocus=Number(cmd.slice(5));S.takeNote='';", "if(cmd.startsWith('take-')&&/^take-\\d+$/.test(cmd)){S.studio.takeFocus=Number(cmd.slice(5));S.takeNote=S.studio.takeReviews[at()+'-'+S.studio.takeFocus]?.note||'';")
s=s.replace("{checks:[0,1,2,3,4,5],decision:issue?", "{machineChecks:['Identität','Zustand','Raum','Handlung','Timing','Artefakte'],decision:issue?")
s=s.replace("return {r,issue:S.studio.takeFocus===2&&!r?.override};", "return {r,issue:shot()?.id==='1E'&&S.studio.takeFocus===2};")
s=s.replace("${issue?'1 Bildbefund':'Keine Befunde'}</span>","${issue?'1 Bildbefund':'Keine Befunde'}${r?.override?' · mit Abweichung gewählt':r?.decision==='Ablehnen'?' · abgelehnt':''}</span>")
s=s.replace("E(S.takeNote||'')", "E(S.takeNote??r?.note??'')")
s=s.replace("if(command==='checks'){", "if(command==='take-review'){S.studio.takeFocus=(S.takes[at()]||[]).includes(S.studio.takeFocus)?S.studio.takeFocus:S.takes[at()]?.[0];S.takeNote=S.studio.takeReviews[at()+'-'+S.studio.takeFocus]?.note||'';S.modal='studio-take-review';dialog();return;}\n if(command==='checks'){")
# All entry points share the same review data.
a=s.index('function reviewEvidence()');b=s.index('function takeAssessment()',a)
s=s[:a]+'''function continuityFindings(){const ids=worldShots();return ids.slice(1).flatMap((i,k)=>{const previous=S.shots[ids[k]],next=S.shots[i];return previous.stateOut!==next.stateIn?[{from:previous.id,to:next.id,index:i,before:next.stateIn,after:previous.stateOut}]:[];});}
function reviewEvidence(){const findings=continuityFindings();return [{name:'Renderbarkeit',status:S.reviewRun?'Bestanden':'Nicht geprüft',detail:'Shotdauer, Quellbindung und Eingabeart · strukturierte Demo-Prüfung'},{name:'Bild / Vorgaben',status:S.reviewRun?'Bestanden':'Nicht geprüft',detail:'Identität, räumliche Vorlage und Shot-Anker · Beispielbefund'},{name:'Continuity',status:!S.reviewRun?'Nicht geprüft':findings.length?findings.length+' Befund(e)':'Bestanden',detail:findings.length?findings.map(f=>f.from+' → '+f.to+': '+f.after+' / '+f.before).join(' · '):'Zustandsfolge in Story-Zeit geprüft'}];}
function runReview(){if(!isEdit()||S.view!=='review')return;S.have.review=true;S.reviewRun=true;S.reviewVersion=S.version;S.reviewFixed=continuityFindings().length===0;const finding=continuityFindings()[0];if(finding)S.selected=[finding.index];S.notice=finding?'Zustandsübergang prüfen':'Prüfung abgeschlossen';render();persist();}
function reviewImage(i){const source=takeSource(i);return source.ready?source.image:'<div class="take-placeholder">'+(S.shots[i].source==='KI-Video'?'Shot-Anker fehlt':'Quellclip fehlt')+'</div>';}
reviewView=function(){
 if(!S.have.review)return emptyView('review');if(!shot())return emptyView('review');const world=worldShots(),idx=world.indexOf(at()),findings=S.reviewRun?continuityFindings():[],finding=findings.find(f=>f.to===shot().id),previous=idx>0?world[idx-1]:null,sequence=S.chronology==='world'?world:S.shots.map((_,i)=>i);
 return `<div class="canvas-caption"><span>${S.chronology==='world'?'Story-Zeit':'Filmfolge · geprüft wird in Story-Zeit'}</span><span>${S.shots.length} Shots</span></div><div class="chronology">${sequence.map(i=>`<button data-shot="${i}" aria-pressed="${at()===i}">${E(S.shots[i].id)}<small>${findings.some(f=>f.to===S.shots[i].id)?'Befund':S.shots[i].id==='1B'?'Rückblende':'→'}</small></button>`).join('')}</div>${findings.length?`<div class="wf-finding-row">${B('wf:show-finding',findings[0].from+' → '+findings[0].to+' · Zustandswechsel',{attrs:`aria-pressed="${!!finding}"`})}<span>${findings.length} offener Befund</span></div>`:''}<div class="review-pair"><div>${previous===null?'<div class="take-placeholder">Beginn der Story-Welt</div>':reviewImage(previous)}<p><b>${previous===null?'Ausgangslage':E(S.shots[previous].id+' · '+S.shots[previous].name)}</b></p><small>Ausgang: ${previous===null?'—':E(S.shots[previous].stateOut)}</small></div><div>${reviewImage(at())}<p><b>${E(shot().id+' · '+shot().name)}</b></p><small>Eingang: ${E(shot().stateIn)}</small></div></div><div class="finding"><h3>${!S.reviewRun?'Prüfung ausstehend':finding?E(finding.from+' → '+finding.to)+' · Zustandswechsel':'Kein Befund für diesen Übergang'}</h3><p>${finding?E(finding.after+' → '+finding.before)+': Der Eingang stimmt nicht mit dem vorherigen Ausgang überein.':'Zustände werden in der Zeitfolge der Story-Welt verglichen.'}</p>${finding?B('review-proposal','Korrektur prüfen',{primary:true,disabled:!isEdit()}):B('wf:evidence','Prüfergebnisse',{cls:'control'})}</div>`;
};
''' +s[b:]
s=s.replace("if(command==='review-proposal'&&shot()?.id!=='1E')return;\n if(command==='review-run'&&isEdit()&&(!S.shots.some(s=>s.id==='1E')||!S.shots.some(s=>s.id==='1D')))S.reviewFixed=true;", """if(command==='review-run'||command==='develop'&&S.view==='review'){runReview();return;}
 if(command==='review-proposal'){if(!isEdit())return;const f=continuityFindings().find(f=>f.to===shot()?.id);if(!f)return;S.reviewProposal=f;S.modal='wf-review-fix';dialog();return;}
 if(command==='apply-review-fix'){const f=S.reviewProposal;if(!f||S.modal!=='wf-review-fix'||!isEdit())return;const target=S.shots.find(s=>s.id===f.to);if(!target)return;S.modal=null;invalidate('plan');target.stateIn=f.after;S.anchorAccepted=S.anchorAccepted.filter(i=>S.shots[i].id!==target.id);S.reviewFixed=!continuityFindings().length;S.selected=[S.shots.indexOf(target)];S.notice=target.id+' korrigiert · Shotplanung erneut freigeben';workflowEnsure();render();persist();return;}
 if(command==='accept-anchor'&&(!hasAnchor(shot()?.id)||S.clay.staleAnchorIds.includes(shot()?.id)))return;""")
s=s.replace("const i=S.shots.findIndex(s=>s.id==='1E');if(i>=0)choose(i);", "const f=continuityFindings()[0];if(f)choose(f.index);")
s=s.replace("workflowBase.action('review-run');", "runReview();")
s=s.replace("shot().id==='1E'&&!S.reviewFixed?'Befund 1D → 1E'", "continuityFindings().some(f=>f.to===shot().id)?'Zustandswechsel prüfen'")
s=s.replace(" if(S.modal==='wf-delete')", " if(S.modal==='wf-review-fix'){const f=S.reviewProposal;workflowDialog('Eingang von '+f.to+' korrigieren',`<div class=\"wf-evidence\"><div><b>Bisher</b><span>${E(f.before)}</span></div><div><b>Vorschlag</b><span>${E(f.after)}</span></div></div><p>Nur der Eingang von ${E(f.to)} ändert sich. Sein Shot-Anker wird erneut erzeugt und gesichtet.</p>`,B('apply-review-fix','In neuer Revision übernehmen',{primary:true}));return;}\n if(S.modal==='wf-delete')")
s=s.replace('readiness=function(){workflowEnsure();return workflowBase.readiness();};',"readiness=function(){workflowEnsure();if(S.view==='review'&&continuityFindings().length)return false;return workflowBase.readiness();};")
p.write_text(s)
p=Path('docs/ui/desktop-production-workbench.js');s=p.read_text().replace('S.takes[i].push(S.takes[i].length+1)','S.takes[i].push(nextTake(i))').replace("if(S.anchors)return {label:'Shot-Anker'", "if(hasAnchor(s.id))return {label:'Shot-Anker'")
s=s.replace("${pic(n,'reference')}","${originalPic(n,'reference')}")
s=s.replace("const anchor=shot().anchorVariant?", "const anchor=!hasAnchor(shot().id)?'<div class=\"take-placeholder\">Shot-Anker fehlt</div>':shot().anchorVariant?")
s=s.replace("return 'Sketch für einen Handlungsmoment fehlt';","{const s=S.shots.find(s=>!s.action.trim()||s.moments.some(m=>!m.asset||m.time<0||m.time>=s.duration));return s?s.id+' · '+(!s.action.trim()?'Handlung fehlt':s.moments.some(m=>!m.asset)?'Sketch fehlt':'Moment außerhalb der Shotdauer'):'Mindestens einen Shot anlegen';}")
s=s.replace("'Fertige Takes bleiben erhalten'","'Fertige Ergebnisse bleiben erhalten'")
p.write_text(s)
p=Path('docs/ui/desktop-production-workbench.studio.js');s=p.read_text().replace('S.takes[i].push(1)','S.takes[i].push(nextTake(i))').replace("S.running=true;q.stage='running';", "undo=[];redo=[];S.running=true;q.stage='running';")
p.write_text(s)
p=Path('docs/ui/desktop-production-workbench.clay.js');s=p.read_text()
s=s.replace("for(const shot of S.shots){const camera=S.clay.cameras[shot.id];if(camera)camera.fov=clayFov(shot);}","""for(const [i,shot] of S.shots.entries()){let camera=S.clay.cameras[shot.id];if(!camera&&S.clay.locations.length){const prior=S.clay.cameras[S.shots[i-1]?.id]||Object.values(S.clay.cameras)[0];camera=S.clay.cameras[shot.id]=prior?clone(prior):{location:S.clay.locations[0].id,start:[5,3,8],end:[5,3,8],target:[0,1,0],poses:{},travel:false};camera.include=false;}if(camera)camera.fov=clayFov(shot);} """)
s=s.replace("S.view==='blocking'&&!clayScene()){checkpoint();Object.assign(c,claySeed());", "S.view==='blocking'&&(c.decision==='skipped'||!clayScene())){checkpoint();if(!c.locations.length)Object.assign(c,claySeed());")
s=s.replace("e.stopImmediatePropagation();checkpoint();if(hit.kind", "e.stopImmediatePropagation();if(hit.kind")
s=s.replace("moved:false};el.setPointerCapture", "moved:false};el.setPointerCapture")
s=s.replace("const dx=e.clientX-d.x,dy=e.clientY-d.y,x=Math.max(-10,Math.min(10,d.hit.world[0]+(f*dx-b*dy)/det)),z=Math.max(-7,Math.min(8,d.hit.world[1]+(a*dy-c*dx)/det));", "const dx=e.clientX-d.x,dy=e.clientY-d.y;if(!d.moved&&Math.abs(dx)+Math.abs(dy)<=2)return;if(!d.moved){checkpoint();d.moved=true;}const xmin=d.hit.kind==='camera'?-12:-6,xmax=d.hit.kind==='camera'?16:6,zmin=d.hit.kind==='object'?-3:xmin,zmax=d.hit.kind==='object'?5:xmax,x=Math.max(xmin,Math.min(xmax,d.hit.world[0]+(f*dx-b*dy)/det)),z=Math.max(zmin,Math.min(zmax,d.hit.world[1]+(a*dy-c*dx)/det));")
s=s.replace("if(clayObjectDrag){clayObjectDrag=null;clayDirty();render();}","if(clayObjectDrag){const moved=clayObjectDrag.moved;clayObjectDrag=null;if(moved)clayDirty();render();}")
s+="""\nfunction splitClay(s,next,u){const cam=S.clay.cameras[s.id];if(!cam)return;const copy=clone(cam),mix=(a,b)=>a.map((v,i)=>v+(b[i]-v)*u);if(cam.travel){const middle=mix(cam.start,cam.end);cam.end=middle;copy.start=clone(middle);}for(const [id,pose] of Object.entries(cam.poses||{})){const middle=Object.fromEntries(Object.keys(pose.start).map(k=>[k,pose.start[k]+(pose.end[k]-pose.start[k])*u]));pose.end=middle;copy.poses[id].start=clone(middle);}S.clay.cameras[next.id]=copy;delete S.clay.outputs[s.id];}\n"""
p.write_text(s)
