from pathlib import Path
p=Path('docs/ui/desktop-production-workbench.js');s=p.read_text()
s=s.replace("schema:5,productionView:null,", "schema:5,workspaceMemory:{},productionView:null,")
s=s.replace("S.cost=which==='Audio'?0.04:0.26;", "S.cost=which==='Audio'?0.04:0.26;if(phase==='board'){S.selected=[4];S.position=shotStart();}")
s=s.replace(":pic(i);}", ":pic(m.sourceShot??i);}")
s=s.replace("Object.assign(moments()[S.moment],{asset:source.asset,frame:source.frame});", "Object.assign(moments()[S.moment],{asset:source.asset,frame:source.frame,sourceShot:source.sourceShot??a.shot});")
s=s.replace("prop('Innerhalb des Shots',moments().length+' Sketches')", "prop('Innerhalb des Shots',moments().length+(moments().length===1?' Sketch':' Sketches'))")
s=s.replace("A → B → C zeigt die Handlung innerhalb eines Shots. Kein Schnitt zwischen den Sketches.", "Zeitpunkte innerhalb derselben Einstellung · keine zusätzlichen Schnitte.")
s=s.replace("${pic(at())}${pic(at(),'reference')}", "${sketchPic(at())}${pic(at(),'reference')}")
s=s.replace("if(verb==='workspace'){visit(param==='production'?(S.productionView||(['edit','finish'].includes(S.current)?'takes':S.current)):param);return;}", "if(verb==='workspace'){if(param===workspace())return;S.workspaceMemory[workspace()]={mediaOpen:S.mediaOpen,mediaFilter:S.mediaFilter,mode:S.mode,moment:S.moment,selected:[...S.selected],position:S.position};const memo=S.workspaceMemory[param];S.mediaOpen=memo?.mediaOpen??false;visit(param==='production'?(S.productionView||(['edit','finish'].includes(S.current)?'takes':S.current)):param);if(memo){S.mode=memo.mode;S.selected=memo.selected.filter(i=>i<S.shots.length);if(!S.selected.length)S.selected=[0];S.position=Math.min(memo.position,total());S.moment=Math.min(memo.moment,moments().length-1);S.mediaFilter=memo.mediaFilter;}render();persist();return;}")
s=s.replace("S.current=S.view=n;S.mediaPreview=false;", "S.current=S.view=n;S.mediaOpen=false;S.mediaPreview=false;")
s=s.replace("if(p==='board'&&S.have.board)actions=", "if(p==='board'&&S.have.board)actions=")
s=s.replace("aria-pressed=\"${S.mode==='animatic'}\"`});", "aria-pressed=\"${S.mode==='animatic'}\"`})+(S.mode==='moments'?`<small>Shot ${shot().id}</small>`:'');")
s=s.replace("if(S.mode==='moments')return", "if(S.mode==='moments')return")
s=s.replace("S.mediaOpen=false;choose(a.shot);if(a.type==='sketch')", "S.mediaOpen=false;choose(a.shot);if(a.type==='sketch')")
s=s.replace("else if(a.type==='reference')S.refMode=a.id.startsWith('anchor-')?'anchors':'identities';", "else if(a.type==='reference'){S.refMode=a.id.startsWith('anchor-')?'anchors':'identities';if(a.id.startsWith('identity-'))S.refSelection=+a.id.split('-')[1];}")
s=s.replace("fixture,action,readiness,editField,choose,position,resize,render", "fixture,action,readiness,editField,choose,position,resize,render,restore")
p.write_text(s)
