from pathlib import Path
p=Path('docs/ui/desktop-production-workbench.workflow.js');s=p.read_text()
a=s.index('function archiveTakes()');b=s.index('function compatibleTakes()',a)
s=s[:a]+'''function rebindMedia(oldID,newID){if(oldID===newID)return;for(const c of S.nle?.clips||[])if(c.asset===oldID)c.asset=newID;for(const record of [S.mediaLocations,S.studio.assetEdits])if(Object.hasOwn(record,oldID)){record[newID]=record[oldID];delete record[oldID];}S.studio.deleted=S.studio.deleted.map(id=>id===oldID?newID:id);S.studio.sourceTabs=S.studio.sourceTabs.map(id=>id===oldID?newID:id);if(S.mediaSelection===oldID)S.mediaSelection=newID;S.mediaMarked=S.mediaMarked.map(id=>id===oldID?newID:id);for(const memo of Object.values(S.workspaceMemory)){if(memo.mediaSelection===oldID)memo.mediaSelection=newID;if(memo.mediaMarked)memo.mediaMarked=memo.mediaMarked.map(id=>id===oldID?newID:id);}}
function activeTakeAssetID(i,t){const shot=S.shots[i],saved=S.archive?.find(a=>a.type==='video'&&a.shotID===shot?.id&&a.take===t&&a.signature===S.takeInputs?.[shot?.id+'~'+t]);return saved?.id||'take-'+i+'-'+t;}
function archiveTakes(){workflowEnsure();for(const [i,takes] of Object.entries(S.takes)){const s=S.shots[i];if(!s)continue;for(const t of takes){const signature=S.takeInputs[s.id+'~'+t],key=s.id+'~'+t+'~'+signature;let saved=S.archive.find(a=>a.key===key);if(!saved){saved={id:'saved-take-'+S.archive.length,key,shotID:s.id,take:t,signature,name:s.id+' · Take '+t+' · Revision '+S.takeRevision,type:'video',review:clone(S.studio.takeReviews[i+'-'+t]||null),duration:s.duration,demoPic:s.art,folder:'footage-scene',origin:'Frühere Revision · Projektmedium'};S.archive.push(saved);}rebindMedia('take-'+i+'-'+t,saved.id);}}}
''' + s[b:]
a=s.index('assets=function()');b=s.index('render=function()',a)
s=s[:a]+'''assets=function(){const active=workflowBase.assets().filter(a=>!a.id.startsWith('anchor-')||hasAnchor(S.shots[a.shot]?.id)).map(a=>{const id=a.type==='video'&&a.shot!==undefined&&a.take!==undefined?activeTakeAssetID(a.shot,a.take):a.id;return {...a,id,...S.studio.assetEdits[id],folder:S.mediaLocations[id]??a.folder};}).filter(a=>!S.studio.deleted.includes(a.id));return [...active,...(S.archive||[]).filter(a=>!S.studio.deleted.includes(a.id)&&!active.some(b=>b.id===a.id)).map(a=>({...a,...S.studio.assetEdits[a.id],folder:S.mediaLocations[a.id]??a.folder}))];};
''' +s[b:]
s=s.replace("if(a?.id?.startsWith('saved-')&&!a.generated)return originalPic(a.demoPic??0", "if(a?.id?.startsWith('saved-')&&!a.generated)return originalPic(a.demoPic??S.shots[a.shot]?.art??0")
s=s.replace("if(S.view==='board'&&shot()&&moments(at()).some", "if(S.view==='refs'&&S.refMode==='anchors'&&shot()?.source!=='KI-Video')$('#nd-inspector').innerHTML='<div class=\"inspector-header\"><b>'+E(shot().id)+' · Quellclip</b><small>Keine Anker-Erzeugung erforderlich</small></div>'+group('Quelle',prop('Datei',shot().sourceFile||'Nicht zugewiesen')+prop('Verwendung',shot().source));if(S.view==='board'&&shot()&&moments(at()).some")
p.write_text(s)
p=Path('docs/ui/desktop-production-workbench.studio.js');s=p.read_text().replace("c.asset??='take-'+c.shot+'-'+c.take", "c.asset??=activeTakeAssetID(c.shot,c.take)");p.write_text(s)
