from pathlib import Path
p=Path('docs/ui/desktop-production-workbench.clay.js');s=p.read_text()
s=s.replace("const clayObjects=()=>clayScene()?.objects||[];", """const clayObjects=(id=shot()?.id,u=null)=>{const cam=clayCamera(id),t=u??(S.clay.time/(S.shots.find(s=>s.id===id)?.duration||1));return (clayScene(id)?.objects||[]).map(o=>{const pose=cam?.poses?.[o.id];if(!pose)return o;return {...o,...Object.fromEntries(['x','z','yaw','scale'].map(k=>[k,pose.start[k]+(pose.end[k]-pose.start[k])*Math.max(0,Math.min(1,t))]))};});};
function clayEditObject(){const o=clayScene()?.objects.find(x=>x.id===S.clay.selection);if(!o)return null;if(o.kind!=='person'&&!o.movable)return o;const cam=clayCamera();cam.poses??={};cam.poses[o.id]??={start:{x:o.x,z:o.z,yaw:o.yaw,scale:o.scale},end:{x:o.x,z:o.z,yaw:o.yaw,scale:o.scale}};return cam.poses[o.id][S.clay.endpoint];} """)
s=s.replace("include:s.source==='KI-Video'", "include:s.source==='KI-Video'&&(i===0||i===4)")
s=s.replace("travel:i===4,fov:clayFov(s)","travel:i===4,fov:clayFov(s),poses:{mouse:{start:{x:i>=3?-1.5:0,z:i>=3?.5:1,yaw:0,scale:.8},end:{x:i>=3?-1.5:0,z:i>=3?.5:1,yaw:i===4?45:0,scale:.8}}}")
s=s.replace("kind:'crate',x:3", "kind:'crate',movable:true,x:3")
s=s.replace("objects:clone(clayScene(s.id).objects)","objects:clone(clayObjects(s.id,0)),endObjects:clone(clayObjects(s.id,1))")
s=s.replace("const objects=isOutput?out.objects:(clayScene(id)?.objects||[])","const objects=isOutput?(el.dataset.clayFrame==='end'?out.endObjects||out.objects:out.objects):clayObjects(id)")
s=s.replace("const field=k.slice(7),bounds=", "const target=clayEditObject(),field=k.slice(7),bounds=")
s=s.replace("if(bounds[field])o[field]=", "if(bounds[field])target[field]=")
s=s.replace("<span>${c.view==='space'?'Freie Ansicht'", "<span>${c.view==='space'?(c.plan?'Draufsicht':'Freie Ansicht')")
s=s.replace("'Räumliche Szene. Ziehen dreht die Ansicht. Objekte im Inspector bearbeiten.'", "'Objekte auswählen und ziehen. Freie Fläche dreht die Ansicht.'")
s=s.replace("'Ziehen: Ansicht drehen · Scrollen: Zoom'", "'Objekte ziehen · freie Fläche dreht die Ansicht'")
s=s.replace("'Freie Ansicht verändert keine Shot-Kamera.'", "'Figuren: dieser Shot · feste Objekte: gemeinsame Location'")
s=s.replace("body=group('Szene',", "body=group('Szene',")
s=s.replace("if(o)body+=group(E(o.name),", "if(o)body+=group(E(o.name),'<small class=\"clay-scope\">'+(o.kind==='person'||o.movable?'Inszenierung · nur Shot '+E(s.id):'Location · alle zugeordneten Shots')+'</small>'+`<div class=\"clay-segment\">${['start','end'].map(x=>CB('endpoint-'+x,x==='start'?'Anfang':'Ende',{attrs:`aria-pressed=\"${c.endpoint===x}\"`})).join('')}</div>`+")
s=s.replace("clayCamera().location=loc.id;clayDirty();", "changed();")
s=s.replace("if(cmd==='inspect'){", "if(cmd==='plan'){c.plan=!c.plan;render();return;}if(cmd==='sketch'){c.sketch=!c.sketch;render();return;}\n if(cmd==='inspect'){")
s=s.replace("else if(cmd==='accept'", "else if(cmd==='accept-all'&&S.view==='blocking'){checkpoint();for(const s of clayIncluded())if(clayOutputValid(s.id))c.outputs[s.id].accepted=true;}\n else if(cmd==='accept'")
s=s.replace("<span class=\"grow\"></span></div>${!Object.keys(c.outputs)", "<span class=\"grow\"></span>${CB('accept-all','Aktuelle Vorlagen sichten',{disabled:!isEdit()||!clayIncluded().some(s=>clayOutputValid(s.id)&&!c.outputs[s.id].accepted)})}</div>${!Object.keys(c.outputs)")
s=s.replace("}).join(''):'<small>Optional</small>'}", "}).join(''):'<small>Optional</small>'}")
old="$('#nd-surface-tools').innerHTML=`<strong>Blocking</strong><span class=\"grow\"></span>${clayScene()?[['space','Raum'],['camera','Kamera'],['outputs','Vorlagen']].map(([id,t])=>CB('view-'+id,t,{attrs:`aria-pressed=\"${S.clay.view===id}\"`})).join(''):'<small>Optional</small>'}`;"
new=old+"if(clayScene()&&S.clay.view==='space')$('#nd-surface-tools').insertAdjacentHTML('beforeend',CI('plan','map','Draufsicht'));if(clayScene()&&S.clay.view==='camera')$('#nd-surface-tools').insertAdjacentHTML('beforeend',CI('sketch','columns-2','Sketch vergleichen'));"
assert old in s;s=s.replace(old,new)
s=s.replace("<span class=\"clay-stage-note\">", "${c.view==='camera'&&c.sketch?'<figure class=\"clay-sketch-overlay\">'+sketchPic(at())+'<figcaption>Storyboard</figcaption></figure>':''}<span class=\"clay-stage-note\">")
s=s.replace("const forward=norm(sub(target,eye))", "if(space&&c.plan){clayPaintPlan(el,ctx,w,h,objects,cam,id,color);return;}\n const forward=norm(sub(target,eye))")
s=s.replace("const poly=(pts,fill,stroke)=>", "if(space)el.clayHits=objects.map(o=>{const p=project([o.x,.8,o.z]),x=project([o.x+1,.8,o.z]),z=project([o.x,.8,o.z+1]);return {kind:'object',id:o.id,x:p.x,y:p.y,world:[o.x,o.z],matrix:[x.x-p.x,z.x-p.x,x.y-p.y,z.y-p.y]};});\n const poly=(pts,fill,stroke)=>")
p.write_text(s)
