import Foundation
import Testing
@testable import NexGenEngine

/// Byte-exact parity of the Swift prompt builders against the Python oracle.
/// Vectors live in `Goldens/prompt-vectors.json`, generated by
/// `scripts/regen-goldens.sh` directly from the Python builders. Each vector
/// carries the full `PromptPayload` plus builder params and the expected string;
/// the test rebuilds the payload and asserts Swift output == expected byte-exact.
@Suite("PromptGolden")
struct PromptGoldenTests {
    struct RefTagJSON: Decodable {
        let role: String
        let bibleId: String
        let hint: String
    }

    struct PayloadJSON: Decodable {
        let subject: String
        let setting: String
        let composition: String
        let camera: String
        let style: String
        let light: String
        let negatives: [String]
        let sheetView: String
        let isStartFrame: Bool
        let durationS: Double?
        let aspectRatio: String
        let nShots: Int
        let multiRefHints: [String]
        let directives: [String]

        func toPayload() -> PromptPayload {
            PromptPayload(
                subject: subject,
                setting: setting,
                composition: composition,
                camera: camera,
                style: style,
                light: light,
                negatives: negatives,
                sheetView: sheetView,
                isStartFrame: isStartFrame,
                durationS: durationS,
                aspectRatio: aspectRatio,
                nShots: nShots,
                multiRefHints: multiRefHints,
                directives: directives
            )
        }
    }

    struct Vector: Decodable {
        let caseName: String
        let builder: String
        let modelId: String?
        let sheetKind: String?
        let hasStartImage: Bool?
        let hasEndImage: Bool?
        let isPacingArm: Bool?
        let referenceTags: [RefTagJSON]?
        let payload: PayloadJSON
        let expectedPrompt: String
    }

    struct VectorFile: Decodable { let vectors: [Vector] }

    static func loadVectors() throws -> [Vector] {
        let url = try #require(
            Bundle.module.url(
                forResource: "prompt-vectors", withExtension: "json", subdirectory: "Goldens"
            ),
            "Goldens/prompt-vectors.json not found in test bundle"
        )
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(VectorFile.self, from: data).vectors
    }

    static func produce(_ v: Vector) throws -> String {
        let payload = v.payload.toPayload()
        let sheetKind = v.sheetKind ?? "character"
        let tags = v.referenceTags?.map { ReferenceTag(role: $0.role, bibleId: $0.bibleId, hint: $0.hint) }
        switch v.builder {
        case "image":
            return try PromptGenerator.buildImagePrompt(
                modelID: v.modelId!, payload: payload, sheetKind: sheetKind
            )
        case "nano_banana":
            return try ImageBuilders.nanoBanana(payload, sheetKind: sheetKind)
        case "gpt_image_2":
            return try ImageBuilders.gptImage2(payload, sheetKind: sheetKind)
        case "imagen":
            return try ImageBuilders.imagen(payload, sheetKind: sheetKind)
        case "runway_image":
            return try ImageBuilders.runwayImage(payload, sheetKind: sheetKind)
        case "video":
            return PromptGenerator.buildVideoPrompt(
                modelID: v.modelId!, payload: payload,
                hasStartImage: v.hasStartImage ?? false,
                hasEndImage: v.hasEndImage ?? false,
                isPacingArm: v.isPacingArm ?? false,
                referenceTags: tags
            )
        case "seedance_2":
            return SeedanceBuilder.build(
                payload,
                hasStartImage: v.hasStartImage ?? false,
                hasEndImage: v.hasEndImage ?? false,
                isPacingArm: v.isPacingArm ?? false,
                referenceTags: tags
            )
        default:
            Issue.record("unknown builder \(v.builder) in vector \(v.caseName)")
            return ""
        }
    }

    @Test("every prompt vector matches the Python oracle byte-exact")
    func allVectorsMatchByteExact() throws {
        let vectors = try Self.loadVectors()
        #expect(!vectors.isEmpty, "no prompt vectors loaded")
        for v in vectors {
            let actual = try Self.produce(v)
            #expect(
                actual == v.expectedPrompt,
                """
                byte mismatch for case \(v.caseName)
                --- expected ---
                \(v.expectedPrompt)
                --- actual ---
                \(actual)
                """
            )
        }
    }

    @Test("vector file covers every builder path")
    func vectorsCoverAllBuilders() throws {
        let vectors = try Self.loadVectors()
        let builders = Set(vectors.map(\.builder))
        for expected in ["image", "video", "seedance_2", "nano_banana", "gpt_image_2", "imagen", "runway_image"] {
            #expect(builders.contains(expected), "no vector exercises builder \(expected)")
        }
    }
}
